### ISSUE TITLE
Bus error: 10 when running meteor run command

### ISSUE THREAD

**Issue by rpong** [Marak/faker.js#1002]
We are encountering "Bus error: 10" when running meteor run command.

Meteor Version: METEOR@1.11

meteor run command stops in 

```
Local package version is up-to-date: url@1.3.1
Local package version is up-to-date: webapp-hashing@1.0.9
Local package version is up-to-date: xolvio:cleaner@0.4.0
```

and then ends in Bus error: 10.

We can consistently reproduce this on Faker 5.1.0. Works fine when we revert back to Faker 4.1.0.

**Comment by menelike** [comment]
confirmed.

**Comment by hernanc** [comment]
Can confirm this as well. Rolling back to 4.1.0 solves the issue.

**Comment by stan-wrl** [comment]
Confirm!

**Comment by jSadoski** [comment]
Confirmed as well

**Comment by jSadoski** [comment]
> Can confirm this as well. Rolling back to 4.1.0 solves the issue.

Thanks @hernanc, that resolved my problem for now.

Is this related? https://github.com/watson-developer-cloud/node-sdk/issues/392

**Comment by zacharytyhacz** [comment]
Can confirm this issue as well, project won't even run...

**Comment by zacharytyhacz** [comment]
> Can confirm this as well. Rolling back to 4.1.0 solves the issue.

this fixes it - thanks bro

**Comment by Philip-Nunoo** [comment]
👍 same issue

**Comment by vojdan** [comment]
Still an issue. Downgrading `faker` to `4.1.0` works.

**Comment by Marak** [comment]
That you for letting us know @rpong 

This should be resolved with the latest published version.

We had published some test and coverage reports in `v5.1.0` causing a very large package to be published.

Can anyone confirm `v5.4.0` fixes this?

CC: @vojdan @Philip-Nunoo @zacharytyhacz @jSadoski @stan-wrl @hernanc @menelike

**Comment by rpong** [comment]
@Marak , tested v5.4.0 and it works for us now at Meteor 2.0. Thank you! 🎉

**Comment by Marak** [comment]
Closing as resolved.

Please let us know if you find anything else.

Thanks everyone!
