### ISSUE TITLE
Code coverage report in npm package

### ISSUE THREAD

**Issue by Allcharles** [Marak/faker.js#1004]
It appears that the npm package for faker@5.1.0 contains the code coverage reports (`reports` folder). This is taking up 30MB of space which is 3x the size of the entire package.

File/Folder Sizes:
![image](https://user-images.githubusercontent.com/3955116/93404765-66cec600-f8ce-11ea-82d1-7969e53b2408.png)

**Comment by mhart** [comment]
Dupe of #998

**Comment by Allcharles** [comment]
You are correct, my bad
