### ISSUE TITLE
Error on upgrade from 4.10 to 5.20 Unable to resolve module `./locales/en_AU_ocker

### ISSUE THREAD

**Issue by approached** [Marak/faker.js#1024]
Error on upgrade from 4.10 to 5.20 

```
error: Error: Unable to resolve module `./locales/en_AU_ocker` from `node_modules/faker/lib/locales.js`:
```

**Comment by pascaliske** [comment]
Hi @approached, I had the same issue but the suggestions in this comment worked for me: https://github.com/Marak/faker.js/issues/981#issuecomment-702520737 😊

**Comment by approached** [comment]
Thank you.

This works for me:
```bash
yarn remove faker
yarn add faker --dev
```
