### ISSUE TITLE
French city doesn't look french

### ISSUE THREAD

**Issue by vulcaryn** [Marak/faker.js#1031]
I would like to use faker to generate some city names based on a locale but it doesn't work well for French cities.

I'm using faker v5.1.0.
```
const faker = require('faker/locale/fr');

console.log(faker.address.city());
console.log(faker.address.city());
console.log(faker.address.city());
console.log(faker.address.city());
```
Returns 
```
North Danykaton
Simonfurt
North Lilaport
West Marciamouth
```

As a French resident, I'm sure these cities don't look like a french city name.
After a quick search in your locales, it appears that you got a list of french cities but they are not used when faking French city. 

Any clues about this problem?

Thanks for your help :)

**Comment by Marak** [comment]
Thank you for your report @vulcaryn 

This should be mostly resolved with: https://github.com/Marak/faker.js/commit/8bd06499b5c9b580295b0946b323748b00099429

The main problem was that `first_name` was missing from `fr` and currently `Address.city` uses `first_name` and `last_name` to generate fake city names.

see:

```js
  this.city = function (format) {
    var formats = [
      '{{address.cityPrefix}} {{name.firstName}}{{address.citySuffix}}',
      '{{address.cityPrefix}} {{name.firstName}}',
      '{{name.firstName}}{{address.citySuffix}}',
      '{{name.lastName}}{{address.citySuffix}}'
    ];

    if (typeof format !== "number") {
      format = faker.random.number(formats.length - 1);
    }

    return f(formats[format]);

  }
```

It would great if someone could add a list of common cities which exist in `fr` so we can add them to the library. I suspect we can generally improve `Address.city`. Any help is appreciated!

**Comment by vulcaryn** [comment]
Hi, thanks for the fix.
About the list of common cities, it appears that https://github.com/Marak/faker.js/blob/master/lib/locales/fr/address/city_name.js already contain some city names. Is it enough ?

**Comment by Marak** [comment]
That looks like a great start.

We just need to open a PR which modifies `Address.city` to use the city definitions if available.

Should be an easy fix. Will accept PR.

**Comment by vulcaryn** [comment]
Looks not quit easy as expected but it works. Tell me if something's wrong.
https://github.com/Marak/faker.js/pull/1106

**Comment by Moosh-be** [comment]
@vulcaryn   #1106 solutionne bien #1031. Donc  cette issue peut être fermée non ?
