### ISSUE TITLE
Coverage reports are included in npm archive

### ISSUE THREAD

**Issue by HackbrettXXX** [Marak/faker.js#1049]
Roughly 30MB of coverage reports are included in the npm archive when running `npm install faker`. Not sure they should be included. It also looks like there is some other stuff that doesn't need to be in the npm archive.

Package Version: 5.1.0

**Comment by tobyhinloopen** [comment]
https://github.com/Marak/faker.js/issues/1046

Maybe create a PR with an `.npmignore`

**Comment by HackbrettXXX** [comment]
Sure, I can create a PR. Which files should be included in the archive? I'd suggest:
- dist folder
- lib folder
- locale folder
- is the vendor folder required?
- index.js
- Readme.md
- logo.png
- package.json

**Comment by vladimiry** [comment]
Consider using whitelisting scenario in `.npmignore` rather than blacklisting, see example (disable all first and then whitelist needed things):
```
/*

!/lib/
!/LICENSE
!/package.json
!/README.md
```

**Comment by HackbrettXXX** [comment]
What about removing the `.npmignore` file and instead using the `"files"` property in the `package.json`?
https://blog.npmjs.org/post/165769683050/publishing-what-you-mean-to-publish

**Comment by vladimiry** [comment]
I personally would not use `files` section of `package.json` since it increases published package size (since listed in `package.json`) and makes `package.json` file less readable.

They say

> File patterns follow a similar syntax to .gitignore, but reversed

But the same scenario can be achieved using `.gitignore` file (see previous message).

**Comment by HackbrettXXX** [comment]
Sorry for the delay. I prepared a PR now.

**Comment by Marak** [comment]
Resolved on `master`
