### ISSUE TITLE
QUESTION: Unpacked size much larger in 5.1.0 (41.4 MB) than 4.1.0 (5.5 MB)

### ISSUE THREAD

**Issue by pete-dunham** [Marak/faker.js#1052]
I was troubleshooting a significant change in my deployment package size and found it to be a x7.5 change from version 4.1.0 of faker at 5.5MB compared to an unpacked size  41.4MB  in faker version 5.1.0.

I was just curious on why the package size saw such a significant increase.

Thanks in advance.

**Comment by alexcroox** [comment]
I'm also having issues deploying my function to AWS Lambda because it has a 60mb overall size limit and faker is taking 41MB of that!

**Comment by alexcroox** [comment]
@Marak it seems the `reports` folder is part of the npm package which is responsible for this size:

![image](https://user-images.githubusercontent.com/1065835/103516517-9c40f480-4e68-11eb-984b-6be7d661ebcb.png)

**Comment by alexcroox** [comment]
Looks like this PR solves this: https://github.com/Marak/faker.js/pull/1067

**Comment by Marak** [comment]
This should be resolved on `master`.

We'll publish a patch version to npm this weekend to help.
