### ISSUE TITLE
Generate links to images not working

### ISSUE THREAD

**Issue by prodtest375** [Marak/faker.js#1054]
Faker js generated links to image currently not working, It shows "AllAccessDisabled" 
<img width="770" alt="Screenshot 2020-11-20 at 10 01 49 AM" src="https://user-images.githubusercontent.com/66716982/99758428-a8226280-2b17-11eb-9a94-93f8cf55a0e9.png">
`faker.image.avatar()` , it give URL as "https://s3.amazonaws.com/uifaces/faces/twitter/codysanfilippo/128.jpg"

**Comment by mkinoshi** [comment]
It is not working for me either.

**Comment by prodtest375** [comment]
Is there any other way to generate imageURL using faker.js ?

**Comment by andy-a-d-nguyen** [comment]
The answer to your question: [The maintainer is not doing this for free anymore](https://github.com/Marak/faker.js/issues/1046)

**Comment by 255kb** [comment]
We are using this lib in [Mockoon](https://github.com/mockoon/mockoon) and are willing to help with this issue. I can dedicate time for this, if @Marak or anyone else is interested. 
I propose that we host the image files where it's completely free, something like firebase hosting + Cloudflare. Or only use Unsplash API which is also free.

**Comment by mitchwd** [comment]
+1 for Unsplash.
