### ISSUE TITLE
Arabic locale does not export name

### ISSUE THREAD

**Issue by ephor** [Marak/faker.js#1057]
Hello! Why Arabic locale does not export the name?  https://github.com/Marak/faker.js/blob/master/lib/locales/ar/index.js

**Comment by Marak** [comment]
@ephor - 

Good catch! Looks like a bug. 

We can just add the missing require statement...but I'd like to know why the tests didn't catch this.

Can anyone follow up and determine why the tests passed for this? We should have locale tests for name?

**Comment by Marak** [comment]
Resolved with https://github.com/Marak/faker.js/commit/4eb3f008bae646d7bc86af289a3ffb6b782052fe
