### ISSUE TITLE
I cannot Fetch files from the server

### ISSUE THREAD

**Issue by fox32-pro** [Marak/faker.js#1061]
It just showing me :
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>DDAA678C14A01AC8</RequestId>
<HostId>JTMN924/IaS9Vq+vN4k9k2W59jXA0hKlo/ZlK7Z32UhbAkrjVKrEYQKpIq1oa/xyFbjp5sziES0=</HostId>
</Error>
Can you Fix it

**Comment by Marak** [comment]
Thanks for letting us know! This is due to the `uifaces` going down.

The old links are no longer valid.

The latest version of `faker` should be generating valid image links again and we are working towards improving images in general.

Closing.
