### ISSUE TITLE
Segmentation fault on 5.1.0

### ISSUE THREAD

**Issue by ad31m0** [Marak/faker.js#1066]
Hello, I'm getting a segmentation fault on version 5.1.0 while using meteor
steps to reproduce

```
meteor create app
cd app
npm install faker@5.1.0 --save
meteor
```
output

```
=> Started proxy.                             
=> Started MongoDB.                           
Segmentation fault (core dumped)
```

- The package is not imported in the code, I don't use it anywhere it happens after installation
- No other packages installed, when I remove faker it builds successfully
- Doesn't happen with faker @4.1.0

**Comment by minhna** [comment]
H have the same problem.
Meteor version 1.12

**Comment by AlanOrtega91** [comment]
Same here with Faker 5.0.0 and Meteor 1.11

**Comment by aureooms** [comment]
I did not investigate the issue back in August 2020 and stayed with meteor 1.10.2 for a while but it seems that indeed faker is to blame. I am now running meteor 2.0 successfully after removing the faker dependency (faker 5.1.0).

**Comment by Marak** [comment]
I'm not using Meteor locally.

If any Meteor users can open a PR to resolve this or at least further investigate it would be appreciated.

**Comment by AlanOrtega91** [comment]
Version 5.2.0 solves this issue for me

**Comment by Marak** [comment]
Can anyone confirm that `v5.2.0` resolves the issue?

@ad31m0  @aureooms @minhna

**Comment by Marak** [comment]
Marking as resolved.

**Comment by aureooms** [comment]
@Marak I confirm it works again with `v5.4.0`. I have not tested `v5.2.0`.
