### ISSUE TITLE
image.avatar() is no longer working

### ISSUE THREAD

**Issue by mattfrancis888** [Marak/faker.js#1076]
For example, this URL generated by image's avatar() no longer works:
https://s3.amazonaws.com/uifaces/faces/twitter/imsoper/128.jpg

I think the servers are made private as mentioned by this issue:
https://github.com/Marak/faker.js/issues/1055

Are there any news on when it will be public again / reason why it's private?

**Comment by ronenteva** [comment]
The avatars are from [uifaces.com](https://uifaces.com/) which was cancelled.

**Comment by marcosdipaoloSV** [comment]
any solution?

**Comment by HossamAbubakr** [comment]
https://uifaces.co/ appears to be a good alternative? maybe it can replace uifaces.com?

**Comment by caiotarifa** [comment]
See #1068.
