### ISSUE TITLE
Using Faker with Meteor leads to ZSH Error

### ISSUE THREAD

**Issue by TheEny53** [Marak/faker.js#1082]
When using Faker(latest) in combination with Meteor unit tests using chai and mocha, the following error occurs:
zsh: bus error  meteor runr 
Fixed by removing the faker package completely, but I think this is not expected behaviour.
Further specs: MAC OSX 11.3, npm v7.3.0, node v15.5.0

**Comment by jchristman-plex** [comment]
Probably related to #1066? I'm curious about why a test data generation tool is causing seg faults and bus errors. Very strange.

**Comment by TheEny53** [comment]
Yes, seems to be related. Wondering as well, as this is definitely very strange behaviour.

**Comment by Marak** [comment]
This should be resolved #1066

@jchristman-plex - I don't use Meteor here, but I suspect the issue was due to a large `./reports` coverage folder accidentally being published to `npm`.

Please try again with the latest version of `faker.js` and let us know if it's resolved. Thanks!

**Comment by jchristman-plex** [comment]
@Marak - confirmed that it fixed my error with Meteor, but I cannot speak to @TheEny53's situation. Thanks for the bugfix!
