### ISSUE TITLE
Regression bug with v5.2.0

### ISSUE THREAD

**Issue by trivigy** [Marak/faker.js#1093]
Looks like in v5.2.0 there was an `hr` locale added but some of the folders imported inside of it's `index.js` do not resolve. In particular `./company` and `./lorem`. https://github.com/Marak/faker.js/blob/v5.2.0/lib/locales/hr/index.js#L5-L7

**Comment by gormonn** [comment]
I have the same issue...

**Comment by Marak** [comment]
I'm tracking this down now. All our tests passed so I'm slightly surprised.

@trivigy @gormonn - Could you tell us what error this actually caused for you?

I'd like to capture this in our test suite.

**Comment by Marak** [comment]
Looks like a missing require was bypassing the locale test for `hr`. 

This should be resolved in `v5.3.1` or higher now.

RE: https://github.com/Marak/faker.js/blob/v5.2.0/lib/locales/hr/index.js#L5-L7

Thanks for letting us know about this! Much appreciated.

**Comment by trivigy** [comment]
@Marak In my case `mocker-data-generator` was causing the issue because it relies on `^5.1.0` version. I was manually overriding it but now hopefully it will be resolved in higher versions. Thanks.

**Comment by gormonn** [comment]
> @Marak In my case `mocker-data-generator` was causing the issue because it relies on `^5.1.0` version. I was manually overriding it but now hopefully it will be resolved in higher versions. Thanks.

I am using mocker-data-generator too.

As a workaround, I've added faker@5.1.0 in the project dependency.
