### ISSUE TITLE
faker.Date.past(1) returns the same date

### ISSUE THREAD

**Issue by DjebbZ** [Marak/faker.js#110]
Hi,

While using with Faker, I noticed the `faker.Date.past(1)` always returned the same date. I think the implementation lacks the number of hours in a day in the formula (`* 24`).

Then I read the test for `past()` and understood nothing. At https://github.com/Marak/Faker.js/blob/v1.1.0/test/date.unit.js#L21, the test says that a past date should be before the refDate but after the current date ?? A past date in the future ??

I advise to try it in the node REPL, and generate dates with the same parameter and compare output visually. You'll see patterns emerging, but not the one expected.

**Comment by tkoomzaaskz** [comment]
I have analysed old issues and PRs and I can see that the issue has been resolved. Additionally, I checked how does `faker.date.past(1)` behaves:

```
> faker.date.past(1)
Mon Mar 16 2015 21:42:13 GMT+0100 (Central European Standard Time)
> faker.date.past(1)
Fri Jun 13 2014 05:56:21 GMT+0200 (Central European Daylight Time)
> faker.date.past(1)
Tue Jan 20 2015 23:37:14 GMT+0100 (Central European Standard Time)
> faker.date.past(1)
Sun May 18 2014 11:11:35 GMT+0200 (Central European Daylight Time)
> faker.date.past(1)
Mon Dec 22 2014 09:23:08 GMT+0100 (Central European Standard Time)
> faker.date.past(1)
Tue Jun 03 2014 18:16:29 GMT+0200 (Central European Daylight Time)
> faker.date.past(1)
Sun Apr 26 2015 16:56:41 GMT+0200 (Central European Daylight Time)
> faker.date.past(1)
Sun Jun 01 2014 04:57:53 GMT+0200 (Central European Daylight Time)
> faker.date.past(1)
Sun Jul 06 2014 16:14:15 GMT+0200 (Central European Daylight Time)
> faker.date.past(1)
Fri Jun 13 2014 05:00:20 GMT+0200 (Central European Daylight Time)
> faker.date.past(1)
Mon May 19 2014 11:47:53 GMT+0200 (Central European Daylight Time)
> faker.date.past(1)
Sun Apr 12 2015 05:38:29 GMT+0200 (Central European Daylight Time)
> faker.date.past(1)
Mon Apr 27 2015 13:20:04 GMT+0200 (Central European Daylight Time)
```

The tests have been impoved  as weel (ba482f10bed1a4e34cf1941bb5728d0a029822a4).

The PR has been merged, I just closed related issues. And so this issue should have been closed as well.
