### ISSUE TITLE
Why it doesn't install 

### ISSUE THREAD

**Issue by RatonBiswas** [Marak/faker.js#1107]
<img width="784" alt="Screenshot_2" src="https://user-images.githubusercontent.com/32263412/107757316-97b50900-6d4f-11eb-9aa9-828238cc8c96.png">

**Comment by Marak** [comment]
There isn't enough information here to determine what's going on.

It doesn't look related to faker.

Please feel free to try posting your entire logs.

**Comment by RatonBiswas** [comment]
solved
