### ISSUE TITLE
Optimize `Finance.transactionDescription`

### ISSUE THREAD

**Issue by Marak** [Marak/faker.js#1108]
I just noticed that `Finance.transactionDescription` is calling `Helpers.createTransaction()` several times in order to create a description.

```js
 /**
   * description
   *
   * @method  faker.finance.transactionDescription
   */
  self.transactionDescription = function() {
    var account = Helpers.createTransaction().account
    var card = faker.finance.mask();
    var currency = faker.finance.currencyCode();
    var amount = Helpers.createTransaction().amount
    var transactionType = Helpers.createTransaction().type
    var company = Helpers.createTransaction().business
    return transactionType + " transaction at " + company + " using card ending with ***" + card + " for " + currency + " " + amount + " in account ***" + account
  }
```

This isn't a great idea since it's calling additional functions we don't need to be calling. We should be able to replace all usage of `Helpers.createTransaction()` here and instead call the required methods directly.

Should be an easy fix for someone to contribute.

**Comment by Carliyke** [comment]
Assigned the returned object to a variable and just keep using it instead of calling it again:

/**
   * description
   *
   * @method  faker.finance.transactionDescription
   */
  self.transactionDescription = function() {
    var transaction = Helpers.createTransaction()
    var account = transaction.account
    var card = faker.finance.mask();
    var currency = faker.finance.currencyCode();
    var amount = transaction.amount
    var transactionType = transaction.type
    var company = transaction.business
    return transactionType + " transaction at " + company + " using card ending with ***" + card + " for " + currency + " " + amount + " in account ***" + account
  }

**Comment by Marak** [comment]
> Assigned the returned object to a variable and just keep using it instead of calling it again:
> 
> /**
> 
> * description
> * @method  faker.finance.transactionDescription
>   */
>   self.transactionDescription = function() {
>   var transaction = Helpers.createTransaction()
>   var account = transaction.account
>   var card = faker.finance.mask();
>   var currency = faker.finance.currencyCode();
>   var amount = transaction.amount
>   var transactionType = transaction.type
>   var company = transaction.business
>   return transactionType + " transaction at " + company + " using card ending with ***" + card + " for " + currency + " " + amount + " in account ***" + account
>   }

Pretty much yes @Carliyke 

It's not a difficult problem to solve. Just needs to get done with the correct process and Pull Request.

We really should be using https://github.com/bestiejs/benchmark.js to compare any performance changes.

**Comment by ognjenjevremovic** [comment]
Hey @Marak 👋 

I've been using *faker.js* from time to time (more often than not whenever I need to set-up a new project and need some seed data to accompany it).
It never occured to me before to contribute back to the project; so here I am 🙂 .

First of, I'd like to thank you for this awesome (time saving) project! 🎉 
This seems like a really trivial, but nonetheless welcoming issue for newcomers to the project (to get familiar with the codebase, as well as contributing guidelines of the project).

I'd like to provide a PR myself if no one is actively working on this issue (and if this hasn't been resolved yet)?

**Comment by Marak** [comment]
@ognjenjevremovic -

The issue is open and we can see there are no associated commits.

Feel free to try a Pull Request.

Thanks!
