### ISSUE TITLE
Module Request: `dataTypes`

### ISSUE THREAD

**Issue by Marak** [Marak/faker.js#1114]
There should be a new top-level module called `dataTypes`.

It would contain methods such as:

 - `Number`
 - `String`
 - `Boolean`
 - `DateTime`
 - `Float`
 - `UUID`
 - `Hexadecimal`
 - `JSON`
 - `Array`

Most of these methods already exist in `Random` module, so we'll want to move those methods to new `dataTypes`. 

We'll want to put in placeholder functions in `Random` for a major version and put in deprecation `console.log` messages so that users don't get a broken API.

**Comment by lbuerste** [comment]
Hi Marak and all others,
I'm brand new to contributing to opensource, but I'm very eager to finally make a contribution. Because this doesn't seem like an issue too complicated, I'll try to figure it out in the next few days and hopefully opening a pull request! :)

**Comment by Marak** [comment]
Awesome @lbuerste 

Looking forward to it!

**Comment by Marak** [comment]
This should be resolved with #1123 

Thank you for your contributions @lbuerste 

Awesome job!
