### ISSUE TITLE
Importing faker directly from locales fails

### ISSUE THREAD

**Issue by bengillies** [Marak/faker.js#1148]
So basically, if I try and import faker directly from e.g.:

```javascript
const Faker = require('faker/locale/en');
```

then it throws an error [here](https://github.com/Marak/faker.js/blob/master/lib/index.js#L75).

It throws here because that getter expects locales to already exist on the class by the time it's called but in e.g. the [en locale import](https://github.com/Marak/faker.js/blob/master/locale/en.js) they're not added until after the class has been instantiated.

The specific line that's triggering that getter from within the constructor function is [this one](https://github.com/Marak/faker.js/blob/master/lib/system.js#L41).

I'm not 100% sure what that's trying to do tbh so I'm not sure what the fix is, but this issue was introduced in the most recent version (5.5.0) if that's any help.

**Comment by Marak** [comment]
Thank you for your report @bengillies 

I can confirm this is happening. Seems to be a regression.

I did a quick `blame` check and didn't immediately see what was changed that caused this.

If anyone can figure out a quick solution we can merge it. If not I should be able to get this patched tonight.

Also, we should 100% have local require tests that will catch this in the future.

**Comment by Marak** [comment]
I think I found the issue. 

The following line: `var mimeTypes = faker.definitions.system.mimeTypes;` at https://github.com/Marak/faker.js/blob/master/lib/system.js#L41 will always be undefined due to changes made in https://github.com/Marak/faker.js/pull/985/files

This was related to a performance optimization in `System` module. We'll have to revert the change or figure out a better solution.

**Comment by Marak** [comment]
@bengillies -

This *should* be resolved in latest version `5.5.1`

We will make sure that the test suite covers this type of require / import style before the next major release version.

Thanks again for your report and please let us know if you find any additional issues.

**Comment by bengillies** [comment]
Thanks for all your speedy work @Marak.
