### ISSUE TITLE
faker.image.imageURL() is not a function

### ISSUE THREAD

**Issue by ssoulless** [Marak/faker.js#1151]
I installed last version of faker in a standard node app, Im using `faker.name.firstName()` and works okay but when I try `faker.image.imageURL()` it says that `TypeError: faker.image.imageURL is not a function`

I installed withing the project folder:

`npm install faker`

that's all I did, and within the script Im:

`const faker = require("faker");`

It should work shouldn't it?

**Comment by Marak** [comment]
Try `faker.image.imageUrl` instead?

**Comment by ssoulless** [comment]
Sorry Im an idiot.
