### ISSUE TITLE
[datatype] Error with typescript

### ISSUE THREAD

**Issue by mtr1990** [Marak/faker.js#1152]
Hi,

I have migrate  random -> datatype (faker.random.number () -> faker.datatype.number ())
and get the following error,

<img width="1011" alt="Screen Shot 2021-03-29 at 17 09 01" src="https://user-images.githubusercontent.com/13531993/112822449-2ab4c300-90b2-11eb-8573-7417543f4b65.png">

Please, how can this be fixed, thanks!

**Comment by Marak** [comment]
Perhaps the Type Script definitions need to be updated?

RE: https://github.com/Marak/faker.js/issues/1023

CC: @mfulton26

**Comment by Superoryco** [comment]
Check out [@types/faker v5.5.0](https://www.npmjs.com/package/@types/faker) @mtr1990
