### ISSUE TITLE
 Deprecation Warning: faker.random.number is now located in faker.datatype.number

### ISSUE THREAD

**Issue by chrys-exaucet** [Marak/faker.js#1156]
I encounter this warnig while running my tests in my react app. 

I used faker this way:

```js
  const age= faker.datatype.number();
 const isMarried= faker.datatype.boolean();
```
   in my test  files.

Is there something I am misusing concerning faker?

````

$ yarn test
yarn run v1.22.10

 console.log
    Deprecation Warning: faker.random.number is now located in faker.datatype.number

      at Random.number (../../node_modules/faker/lib/random.js:37:13)

  console.log
    Deprecation Warning: faker.random.number is now located in faker.datatype.number

      at Random.number (../../node_modules/faker/lib/random.js:37:13)

  console.log
    Deprecation Warning: faker.random.boolean is now located in faker.datatype.boolean

      at Random.boolean (../../node_modules/faker/lib/random.js:131:13)

  console.log
    Deprecation Warning: faker.random.boolean is now located in faker.datatype.boolean

      at Random.boolean (../../node_modules/faker/lib/random.js:131:13)

  console.log
    Deprecation Warning: faker.random.number is now located in faker.datatype.number

      at Random.number (../../node_modules/faker/lib/random.js:37:13)

````

dependencies
 - faker@5.5.2
- react@17.0.2
- yarn@1.22.10
 - jest@26.6.2

System:
- OS: Windows 10 10.0.19042
- CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
- Memory: 2.16 GB / 15.85 GB

**Comment by Marak** [comment]
The methods have been moved. Follow the instructions printed on the screen and you'll be fine.

**Comment by chrys-exaucet** [comment]
I am afraid you did not read me carefully. I followed the instructions given by the console output and changed the methods accordingly ( as mentionned above). Turns out  warngins are still being logged.

**Comment by Marak** [comment]
I'd double check your local environment or try again.

*test.js*
```
var faker = require('faker');
const age= faker.datatype.number();
const isMarried= faker.datatype.boolean();
```

```
npm install faker
+ faker@5.5.2
added 1 package from 1 contributor and audited 1 package in 1.236s
found 0 vulnerabilities

% node test.js 
% 

```

Outputs nothing. You probably missed something else in your app.

**Comment by chrys-exaucet** [comment]
Fine then, I'll  investigate.

**Comment by chrys-exaucet** [comment]
Fixed! I had a set of hidden faker.random.* not changed.in deep project files

**Comment by paulo-darocha** [comment]
faker.**database**.random()

**Comment by gamemumu** [comment]
> Fixed! I had a set of hidden fakersrandom.* not changed.in deep project files

Could you show me up?
