### ISSUE TITLE
Errors with Uglify after upgrading to 5.5

### ISSUE THREAD

**Issue by brockfanning** [Marak/faker.js#1157]
Hi all,

After upgrading from 5.4.0 to 5.5.2 I am getting errors during my build process complaining about [the line in finance.js that uses "let"](https://github.com/Marak/faker.js/blob/master/lib/finance.js#L114). Here is the error I'm getting:

```
ERROR in request.bundle.js from UglifyJs
Unexpected token: name (formattedString) [./node_modules/faker/lib/finance.js:114,0][request.bundle.js:65428,10]
```

I'm not an expert in such matters but my understanding is that ES6 code will not work with Uglify, and "let" is ES6. I assume I could add some transpilation somewhere that would take care of the problem. But I just thought I would bring it up here in case you were not aware. An argument could be made for using "var" until 6.0.0, so that downstream projects don't have to change their build processes until the next major version.

I did a search for "let" in the codebase and it is only used in 2 places. If this is of interest, I'd be happy to submit a PR. If not and you prefer to continue using ES6, feel free to close this.

**Comment by Marak** [comment]
Thank you for the report @brockfanning 

Those `let` statements shouldn't have slipped in.

A PR would be welcome to remove them. We should update the linting rules as well.

I think `v6.0.0` will be upgraded to allow ES6 syntax.
