### ISSUE TITLE
Mythology namespace available on Faker Cloud but not in Faker.js

### ISSUE THREAD

**Issue by Ry-DS** [Marak/faker.js#1179]
I'm looking to use faker to generate imaginary planet/star names and found the Mythology section on [Faker Cloud](https://fakercloud.com/api#Mythology) to be perfect for this. However, this namespace is not in this repo!

Is it a premium feature on faker cloud? If not, is it possible to add this module to faker.js?

Thanks :)

**Comment by Marak** [comment]
> is it possible to add this module to faker.js?

Yes.
