### ISSUE TITLE
Lack of randomness in faker.internet.domainName()

### ISSUE THREAD

**Issue by gugu** [Marak/faker.js#1181]
currently faker.internet.domainName() returns <first_name>.<tld>. There are not a big choice of first names and probability to get a duplicate is high. It would be nice to have it like `faker.random.alphaNumeric(12) + '.' + faker.internet.domainSuffix()`

```javascript
self.domainName = function (alphaNumeric) {
     return (alphaNumeric ? faker.random.alphaNumeric(12) : faker.internet.domainWord()) + "." + faker.internet.domainSuffix();
};
```

**Comment by Marak** [comment]
Thank you for your contribution @gugu 

I agree, we could improve `faker.internet.domainName` by adding more entropy / randomness to the function.

Will accept a Pull Request for this. Please be sure that all domain names generated are valid.

**Comment by gugu** [comment]
done. Please tell if I missed something
