### ISSUE TITLE
Differences between faker cloud and faker.js

### ISSUE THREAD

**Issue by IanVS** [Marak/faker.js#1183]
I'm just getting started learning and using faker, and I was looking through the examples at https://fakercloud.com/api to see examples of each of the types that are available.  I found one that seemed perfect, but then noticed that it's not in the README on this repo.  I've been looking through the code a bit to see if it's named differently, but can't find it, so I assume that maybe there are additional data types in faker cloud that are not in the core library, although this isn't clarified anywhere that I can find.  

I see a similar question was asked in #1179, but was closed and locked without much (any) explanation.  As a new user, I'm wondering what the plan is for faker.js and faker cloud.  If they're different and have different capabilities, that's fine and of course your prerogative.  But maybe there can be some kind of indication on https://fakercloud.com/api which ones are cloud-only, to avoid confusion?

**Comment by Marak** [comment]
If you have any questions about Faker Cloud you can try opening an issue over at https://github.com/faker/faker-cloud

Cheers.
