### ISSUE TITLE
Cretit card information is availabe?

### ISSUE THREAD

**Issue by crisfcodes** [Marak/faker.js#1198]
I want to use faker js to generate credit card information, in [Api methods](https://github.com/Marak/faker.js/blob/master/Readme.md#api-methods) section, especifically in `finance`, you can find `creditCardNumber` and `creditCardCVV`, if you try to use this methods, your IDE thrown an error because this methods doesnt exist in faker package.

how can I generate this type of information with fake? 

credit card cvv
credit card number
credit card expiration date

**Comment by MilosPaunovic** [comment]
Hello @crisfcodes,

Have you tried to do it like in the example below?

```js
var faker = require('faker');

var randomCVV = faker.finance. creditCardCVV(); // 706
var randomNumber = faker.finance. creditCardNumber(); // 6759-1952-7978-3077-959
var randomDate = faker.date.future(); // 2021-12-01T15:51:37.808Z
```

What is left for you is to format date in your desired output.

**Comment by jcubic** [comment]
It seems that the credit card is invalid, the number is too short. If this is real fake data the card should pass checksum, otherwise it's useless.
