### ISSUE TITLE
faker.image.avatar & faker.internet.avatar are dead

### ISSUE THREAD

**Issue by AaronNGray** [Marak/faker.js#1206]
I am getting the following back from the ```https://s3.amazonaws.com/uifaces/faces/twitter/zforrester/128.jpg``` URL's
```
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>JCNZT3N8YNVZBCTF</RequestId>
<HostId>SYjrM43OEhh/ICA9n7S9Y6xRu79SvvO1OB59PvTQh299baM+3hbmCXqHWUvt++73Pl5/CUTOG/0=</HostId>
</Error>
```

**Comment by Marak** [comment]
Any links to the old amazon bucket should be removed in latest published versions.

Feel free to update to latest and try again.

**Comment by AaronNGray** [comment]
I have faker 5.5.3 and I still get this message for image URL's.

**Comment by AaronNGray** [comment]
@Marak - okay tried it raw and I am getting :- https://cdn.fakercloud.com/avatars/jeremyworboys_128.jpg

Sorry for the noise, now to figure out what I am doing wrong to retained the old versions data.

**Comment by AaronNGray** [comment]
Okay I am using https://github.com/w3tecch/typeorm-seeding and updated that to use faker@^5.5.3, I totally rebuilt it, and am now getting warnings on **number**, but I am still getting the old URL's not the cdn.fakercloud.com ones I get with my quick raw test of faker, so I am well confused now.

**Comment by temiwale88** [comment]
This worked for me. Thanks @Marak!
