### ISSUE TITLE
I can't to create a phoneNumber based on my regex?

### ISSUE THREAD

**Issue by miladezzat** [Marak/faker.js#1208]
I want to create PhoneNumber base my regex as a pattern: '^01[0125][0-9]{8}$'?
Hi @Marak  you close the issue with no reply man? are this possible or not in the package if you possible I can create a pr for adding it

**Comment by MilosPaunovic** [comment]
At the moment, `phoneNumber` method looks like this:

```js
self.phoneNumber = function (format) {
  format = format || faker.phone.phoneFormats();
  return faker.helpers.replaceSymbolWithNumber(format);
};
```

So, you could either get a completely random number and format, or you could pass a format using this syntax `####-####-##` which will result in string like this one `1234-1234-12`.

This leads to concrete answer to your question, no, it's not posible to invoke `phoneNumber` function with regex as a format parameter.

**Comment by miladezzat** [comment]
we can create a new helper method to create database regex by using this npm package: https://www.npmjs.com/package/randexp 

@MilosPaunovic

**Comment by MilosPaunovic** [comment]
The point of `faker` is to be sufficient on it's own, so I think that using external libraries as dependencies is not really a viable option.

Is there a reason why you couldn't use mentioned package directly?

**Comment by miladezzat** [comment]
We can add this feature to `faker` without use this package.

I suggest this package but we can do this feature without using this package.

**Comment by miladezzat** [comment]
@MilosPaunovic
