### ISSUE TITLE
ar locale only works for names, not lorem?

### ISSUE THREAD

**Issue by mysterybear** [Marak/faker.js#1213]
Hi, I'm calling the `lorem` namespace as well as names. I'm getting Arabic names, but the Lorem is still Latin.

**Comment by PhiLhoSoft** [comment]
That's the definition of [lorem ipsum](https://fr.wikipedia.org/wiki/Lorem_ipsum)…

**Comment by PhiLhoSoft** [comment]
Have you tried to generate it? I went to the page https://ar.lipsum.com/feed/html which is still latin.
The page you show is a page of explanations of what is lorem ipsum. That's what is translated on this site. Not the generated text.

**Comment by mysterybear** [comment]
@PhiLhoSoft ah, point taken, yes, you're right

I still think it would be useful to be able to generate gibberish in the different language scripts that exist, e.g. Arabic as well as Latin, but I guess I'll close this now, thanks for the replies! :)
