### ISSUE TITLE
Filter names based on gender

### ISSUE THREAD

**Issue by yahiarefaiea** [Marak/faker.js#1229]
This is more like a question. Can I generate/filter a name (name.firstName) based on gender?
My goal is to generate boys' names. Is that possible?

**Comment by MilosPaunovic** [comment]
You can send parameters `0` (for male) and `1` (for female) names for `firstName` and `lastName` functions.

Example: `faker.name.firstName(1)`

**Comment by yahiarefaiea** [comment]
Thanks, @MilosPaunovic for your unexpected quick help!
I'll close this issue.
