### ISSUE TITLE
Incremental browser builds for locale data

### ISSUE THREAD

**Issue by Marak** [Marak/faker.js#125]
Currently gulp will concat all locale data into a single pack for the browser.

In production, it might not be acceptable to load the ( large ) bundle containing all locale data.

The build script should be able to create packs based on locale settings that only bundle the requested locale data.

**Comment by kevinburkeshyp** [comment]
Any update/workaround here?

**Comment by tkoomzaaskz** [comment]
This seems a pretty important issue. I've done some research:
* `gulp` uses browserify against [index.js](index.js) file
* [index.js](index.js) contains `var locales = exports.locales = require('./lib/locales');` line, which loads all locales:
```js
var faker = require('../index');
exports['de'] = require('./locales/de.js');
exports['de_AT'] = require('./locales/de_AT.js');
exports['de_CH'] = require('./locales/de_CH.js');
exports['en'] = require('./locales/en.js');
[...]
```
* as a result, everything (all languages) comes bundled.

I was thinking about browserify's [partition-bundle](https://github.com/substack/browserify-handbook#partition-bundle), but I need to do more research.

**Comment by Marak** [comment]
@tkoomzaaskz -

This is a complex issue.

I'd recommend pushing this off until the next major version.

If anyone wants to take charge of this issue, please do. If no, I can do it in time.

**Comment by Marak** [comment]
@kevinburkeshyp - The workaround is probably to remove the require statements from the index.js file and rebuild.
