### ISSUE TITLE
faker.internet.color not producing valid colour literals

### ISSUE THREAD

**Issue by FLamparski** [Marak/faker.js#143]
Often, calling `faker.internet.color()` will produce strings that are less than 7 characters. It should consistently produce colour literals of the form `#RRGGBB`.

Reproducible in master:

```
> faker.internet.color()
'#69694d'
> faker.internet.color()
'#55c61'
> faker.internet.color()
'#46803d'
> faker.internet.color()
'#4132d'
> faker.internet.color()
'#1d245b'
> faker.internet.color()
'#a535a'
> faker.internet.color()
'#731773'
> faker.internet.color()
'#9458'
> faker.internet.color()
'#433242'
> faker.internet.color()
'#21f18'
```

In this one, every other call produces an invalid colour code.

**Comment by Marak** [comment]
Appears to be merged and resolved.

Closing.
