### ISSUE TITLE
faker.definitions.lorem.words gets affected by calling things like faker.lorem.sentence

### ISSUE THREAD

**Issue by rubenstolk** [Marak/faker.js#159]
After calling faker.lorem.sentence a couple of 1000 times, the words array almost only contains undefineds

**Comment by FotoVerite** [comment]
This looks good to me, is there anyway to test it fixes the issue listed above Code is way cleaner regardless and more understandable..

**Comment by Denich** [comment]
+1 Faced

**Comment by rubenstolk** [comment]
Why is this repository so badly maintained. This is a severe bug...

**Comment by nloyola** [comment]
+1
Please fix.

**Comment by csaintc** [comment]
:+1:

**Comment by Marak** [comment]
Why hasn't this been fixed @FotoVerite or @tkoomzaaskz?

I shouldn't have to come in to easy issues like this this to figure out why you haven't followed up with the developers who are trying to contribute.

**Comment by Marak** [comment]
It looks like this was fixed with aa242f7a4bf0cfd15ebcb7f5dcd799d27de6792b and should be resolved and released.
