### ISSUE TITLE
generate card numbers in finance module

### ISSUE THREAD

**Issue by awinogradov** [Marak/faker.js#169]
You can use [gist](https://gist.github.com/B-Con/4988902) for this. Maybe if i find some time i do this?

**Comment by Marak** [comment]
Sounds goods

**Comment by FotoVerite** [comment]
Sounds good. I'm curious why you feel it fits best in the finance module?

**Comment by verybigman** [comment]
Because card is on of many payments methods and contain human finance information. @FotoVerite do you think otherwise?

**Comment by Marak** [comment]
@verybigman - Any updates on a pull request for this?

**Comment by verybigman** [comment]
I return to this issue in the next week, man!:)
Чт, 9 апр. 2015 г. в 21:20, Marak <notifications@github.com>:

**Comment by Marak** [comment]
@verybigman - Any updates on a pull request for this?

:-)

**Comment by verybigman** [comment]
@Marak Sorry! I do not have time for it now :(

**Comment by thebergamo** [comment]
Maybe I can do this =D

**Comment by Marak** [comment]
Should be somewhat easy @thebergamo, let us know with a PR if you can.

**Comment by zpiman** [comment]
Ehm... Hello, is this this still alive? I sort of implemented this feature....

**Comment by awinogradov** [comment]
nobody here :( it's already unneeded feature :(

**Comment by zpiman** [comment]
Well I needed it :smile:... From what I understand, the last attempt to add it failed because of library licensing problems...

**Comment by Marak** [comment]
#382 has been merged.

Should have this functionality shipped in the next release.

Closing.

**Comment by armand1m** [comment]
Hi, is this on the docs?

**Comment by armand1m** [comment]
Well, no it isn't. I'm going to use this library in a project now and I'll also submit a pull request adding API details to the README.md
