### ISSUE TITLE
Can't find documentation?

### ISSUE THREAD

**Issue by geoguide** [Marak/faker.js#170]
Maybe I'm just being oblivious, but I can not find documentation for faker.js I'm looking for how to use some of the non-obvious methods. For instance a method to give me one of a number of values in an array. Randomize? Or does that just mix it up? Sorry if I'm just missing it, but if it doesn't exist perhaps I could help write it.

Thanks.

**Comment by dmamills** [comment]
To get a random element from an array with faker you can the function `randomize` which is just an alias for `array_element`.

```
var a = [1,2,3,4,5,6,7,8,9,10];
var randA = faker.helpers.randomize(a);
var randB = faker.random.array_element(a);
```

**Comment by Marak** [comment]
@geoguide -

It would be nice to have better documentation for the project.

If you have any suggestions or updates please put them together in a pull request. We will accept improvements to documentation.

Thanks!

**Comment by tkoomzaaskz** [comment]
I'd definitely start with replacing the great one-liner of `<ul><li>...</li></ul>` in Readme.md with markdown list syntax. Adding new generators shoudl include updating the docs.

And +1 for @dmamills - I agree, that the docs could be better.

Anyway, I see this library extremely useful, but the speed of development / accepting PRs is rather slow. @Marak do you consider involving new people to accept contributions for thisproject? I would contribute myself, but I don't want to wait 3 months for a response (and this is what I can see, basing on severalissues I've taken a look at).

**Comment by dmamills** [comment]
Improving the docs would be awesome!

I agree with @tkoomzaaskz. I use this library for almost all of my javascript projects. I'd love to be able to help support this project if you'd be open to letting contributors help keep things moving along a bit faster. I know I'd be completely respectful to any visions or guidelines you have for this library.

**Comment by tkoomzaaskz** [comment]
So it's already two of us :beers:

**Comment by Marak** [comment]
I'm trying my best to keep up with the contributions and make several stable releases per year.

It's hard for me because I haven't been getting any revenues for sometime. I have no money. As much as I'd love to spend a few hours a week to get faster releases out, at the time I literally can't afford to do it.

The best way to keep the project moving is to help answer incoming github issues, review incoming pull requests for problems, and try to alert me a few times if there is a mission critical bug that requires immediate fixing. I'll do my best to keep things moving.

If anyone really wants to help, a donation to the project will give me time, which I could spend moving things along. 1J7QqHnkXNF3wQkQBdSnjjvbHp7GMCoxHL If anyone actually sends a significant amount, I'd be glad contract out some of the smaller issues to other open-source developers.

- Marak

**Comment by tkoomzaaskz** [comment]
@Marak, @FotoVerite: The community appreciates creating and maintaining faker.js, as you can see with the number of stars of the github repository. However, I think you can't *expect people to pay you for doing open source*, this is not the idea. Some developers here offer PRs that are awaiting verification long time. As a result, it discourages others from contributing and eventually the project growth is really slow - comparing to how many people use it. 

Being far away from discussing anyone's private situation, I think it's better to nominate new maintainers (if you don't have time to do that on your own, granting access in github and npm) rather than blocking the library and persuading the community fork this library.

**Comment by Marak** [comment]
@tkoomzaaskz -

Thanks for your input. I will continue to perform release cycles as best I can.

If you want to have more influence into what happens with the project you should first consider contributing more before dictating how you think things should be. If you aren't happy with the speed of the releases, you can prepare the next release yourself, starting right now. 

If you can prove you can make a good release candidate, I will gladly add you ( or any other person ) to the project. I want people to help.

- Marak

**Comment by Marak** [comment]
@tkoomzaaskz - A good start for you would be making the improvements to the documentation you already suggested earlier in this thread.

**Comment by tkoomzaaskz** [comment]
Ok, I'll use master branch for that. Do you use parallel branches for managing releases?

**Comment by Marak** [comment]
The best way to do it is create a fork with a new branch called "2.1.3".

From here we can merge into master.

**Comment by Marak** [comment]
@tkoomzaaskz - I added you as a contributor to the faker.js project on Github.

You can now work in a new branch for the release on the main repo.

Please take care in managing issues and pull requests. Stay out of the master branch for the time.

Good luck and thanks!

- Marak

**Comment by dmamills** [comment]
+1 Thanks @Marak

**Comment by tkoomzaaskz** [comment]
Thank you. Expect first contribution this weekend.

**Comment by tkoomzaaskz** [comment]
I can see that there are quite many opened issues that are either already resolved or invalid. Think I'll be working on those.

**Comment by tkoomzaaskz** [comment]
@Marak I'm ready to merge #200 into `master`. Only the docs were updated, the code remains untouched. I'd have done it myself, but thought it's better to get your approval before. See the new docs at: https://github.com/tkoomzaaskz/faker.js

**Comment by Marak** [comment]
@tkoomzaaskz -

I have posted feedback on #200

**Comment by tkoomzaaskz** [comment]
@Marak thanks for the feedback. Please take a look at the `CONTRIBUTING.md` file I've prepared. Meanwhile, I'll work on the auto-gulp-readme update. Then I'll dive into the code.

**Comment by tkoomzaaskz** [comment]
PS @Marak am I right that you haven't added your last commit (c0dc1c49a95c87cece7458c4099429fb7556de6a) to the docs sources either?

    ### CLI ( Command Line Tool )
    
    see: https://github.com/lestoni/faker-cli

**Comment by Marak** [comment]
@tkoomzaaskz -

I don't have the availability to answer all your questions.

Please prepare all your work in a separate `dev` branch and prepare the new release. When you have a release ready I will review all commits for that release and determine if we can merge.

- Marak

**Comment by tkoomzaaskz** [comment]
@Marak, I have prepared new release for `2.1.3` version in #209. Please take a look at it. There is also `v2.1.3` branch that contains all release commits, it's supposed to be ready to be merged into `master` and afterwards `npm publish` to release `2.1.3` in npm.

All other question I asked can be postponed, I would like to include them into next releases. The sooner we can release the new version, the sooner I'll start working on code.

**Comment by tkoomzaaskz** [comment]
This topic got overbloated somehow already. It'd be nice to have a documentation including usecases of faker generators. But this requires a separate issue afaik. Please, open a new issue and suggest how you see it.

**Comment by cliffpyles** [comment]
@Marak Thanks for providing such an awesome product! I agree that documentation would be extremely helpful, and I'm interested in putting this together. Is that something that you still see as a priority, and if I spend the time to put something together, will it definitely be used (assuming they are accurate)?

**Comment by brianmcmillan** [comment]
Please take a look at the wiki. I did an initial pass at the documentation by looking at the source code and it would be FANTASTIC to have another set of eyes!

**Comment by cliffpyles** [comment]
Thanks Brian. That's exactly what I was looking for. If I see something to add, what's the process for contributing?

**Comment by cliffpyles** [comment]
@brianmcmillan This appears to be exhaustive. Have any objections to me breaking the sections into individual pages, and adding syntax highlighting to the code blocks?

**Comment by Marak** [comment]
It would be great if this information existed as data instead of markdown.

That way we could auto-generate documentations.

Either as JSON literals next to the code blocks, comments they can be parsed out as data using a tool, or even a stand-alone schema file per module.

**Comment by cliffpyles** [comment]
Are you thinking of something like JSDoc?

**Comment by Marak** [comment]
Tough call. It might make sense to just polish the documentation we have in the wiki since the `faker` API is relatively stable.

What I'd like to have is an `mschema` available for every method and module. This would also allow for uniform validation of all existing method input arguments. The additional overhead of adding this in-line to the code wouldn't be too bad.

https://github.com/mschema/mschema

Note: We wouldn't have to take `mschema` as a npm dependency into `faker`, we can simply follow it's formatting.

For example in `internet.js` we have `email` method:

```js
self.email = function (firstName, lastName, provider) {
  provider = provider || faker.random.arrayElement(faker.definitions.internet.free_email);
  return  faker.helpers.slugify(faker.internet.userName(firstName, lastName)) + "@" + provider;
};
```

Adding a schema in-line would look something like:

As an expanded form:

```js
self.email.schema = {
  "description": "Generates a valid email address based on optional input criteria",
  "sampleResult": "foo.bar@gmail.com",
  "properties": {
    "firstName": {
      "type": "string",
      "required": false,
      "description": "The first name of the user"
    },
    "lastName": {
      "type": "string",
      "required": false
    },
    "provider": {
      "type": "string",
      "required": false
    }
    
  }
};
```

With `mschema`, this could be abbreviated to:

```js
self.email.schema = {
  "description": "Generates a valid email address based on optional input criteria",
  "sampleResult": "foo.bar@gmail.com",
  "properties": {
    "firstName": "string",
    "lastName": "string",
    "provider": "string"
  }
};

```

It might take some experimentation, but once we get the right schema structure imposed, you'll find iterating through an `mschema` object to generate mark-up is pretty easy.

You could also generate the code examples since we have all the method names, properties, and an expected `sampleResult`

**Comment by cliffpyles** [comment]
Nice. I really like this approach. You had mentioned having the schema in a stand-alone file also. That would eliminate noise in the modules themselves. Is that the preferred approach, and if so, where should those files live?

**Comment by Marak** [comment]
I'd like to keep it in-line with the modules instead of separate files. Easier to read.

We could add an option to the browser build step to remove these properties if someone wanted to reduce browser package size.

**Comment by brianmcmillan** [comment]
No, I don’t have any objections at all. 
~ Brian

**Comment by brianmcmillan** [comment]
I think the idea of incorporating msschema into the code is a great idea. It’s much cleaner than JSON schema. Another alternative might also be to use joi (https://github.com/hapijs/joi <https://github.com/hapijs/joi>). My vote is to go with msschema in the code and then auto-generate a documentation file.

~ Brian

**Comment by cliffpyles** [comment]
Awesome. I think everyone is on the same page then. I'll get started on the updates. I'll update the wiki first, since it will only take a few minutes. Then I'll start on the schemas this evening.

**Comment by cliffpyles** [comment]
I've created the individual pages on the wiki, but I left the original page with all of the methods. If everyone is happy with the individual pages, I will remove the old page so we don't have duplicate information. That sound good to everyone?

**Comment by brianmcmillan** [comment]
@cliffpyles Great job. Feel free to delete the old page.

**Comment by cliffpyles** [comment]
@brianmcmillan @Marak 

Old page deleted on the Wiki.

I've also completed round 1 for the internet module. Let me know if you guys have any thoughts or feedback. You can view the work here: https://github.com/cliffpyles/faker.js/blob/master/lib/internet.js

There were a couple of things that came to my attention though. 

1st - On some schemas (email for example) it seems like it will be useful to list multiple examples. In this instance I pluralized the field name of sampleResult, and used an array of strings. It's not my favorite approach, but the convention is meant to eliminate confusion when other methods actually send an array back as a response. Any ideas for a better approach?

2nd - Would it be helpful if I included a field for examples of usage as well?

**Comment by Marak** [comment]
@cliffpyles -

Looking very nice.

I'd recommend we move to only using `sampleResults` as an array. Remove `sampleResult`. In the case of a single result, it would be a single item array. Will be easier down the road for building tools to parse the schema.

As for example usage, my idea was we could auto-generate the example usage code based on the new schemas and the structure of faker. Everything we need to generate code examples *should* be there. Let me know if find an example where we might need additional information.

**Comment by Marak** [comment]
@cliffpyles -

Any updates? I'll be publishing a new version of faker soon, would like to include this.

**Comment by cliffpyles** [comment]
@Marak I've been pulled away to work on some other stuff. I'll pick it back up this weekend. When do you want it completed by?

**Comment by Marak** [comment]
@cliffpyles 

I've actually got some local changes that will help you moving forward.

I'll review and merge what you have and see if I can combine our efforts.

I'll try to update this before Friday. Until then, I would refrain from updating any other modules.

Thank you for your continued contributions.

**Comment by Marak** [comment]
@cliffpyles 

I've gone ahead and merged your branch into `master`.

What I've done is created a script which generates complete mschema definitions based on the both the structure of the project, and any available in-line schemas.

For any methods which are missing schema definitions, the script parses the function code and is able to pull out the argument names as strings. From here, I assign the `any` type.

This script will be super useful down the road. I've pasted the current output below ( which contains your now merged schemas ).

Any time you can spend adding additional schema definitions would be much appreciated.

```json
{ methods: 
   { type: 'string',
     enum: 
      [ 'random.number',
        'random.arrayElement',
        'random.objectElement',
        'random.uuid',
        'random.boolean',
        'random.word',
        'random.words',
        'random.image',
        'helpers.randomize',
        'helpers.slugify',
        'helpers.replaceSymbolWithNumber',
        'helpers.replaceSymbols',
        'helpers.shuffle',
        'helpers.mustache',
        'helpers.createCard',
        'helpers.contextualCard',
        'helpers.userCard',
        'helpers.createTransaction',
        'name.firstName',
        'name.lastName',
        'name.findName',
        'name.jobTitle',
        'name.prefix',
        'name.suffix',
        'name.title',
        'name.jobDescriptor',
        'name.jobArea',
        'name.jobType',
        'address.zipCode',
        'address.city',
        'address.cityPrefix',
        'address.citySuffix',
        'address.streetName',
        'address.streetAddress',
        'address.streetSuffix',
        'address.streetPrefix',
        'address.secondaryAddress',
        'address.county',
        'address.country',
        'address.countryCode',
        'address.state',
        'address.stateAbbr',
        'address.latitude',
        'address.longitude',
        'company.suffixes',
        'company.companyName',
        'company.companySuffix',
        'company.catchPhrase',
        'company.bs',
        'company.catchPhraseAdjective',
        'company.catchPhraseDescriptor',
        'company.catchPhraseNoun',
        'company.bsAdjective',
        'company.bsBuzz',
        'company.bsNoun',
        'finance.account',
        'finance.accountName',
        'finance.mask',
        'finance.amount',
        'finance.transactionType',
        'finance.currencyCode',
        'finance.currencyName',
        'finance.currencySymbol',
        'image.image',
        'image.avatar',
        'image.imageUrl',
        'image.abstract',
        'image.animals',
        'image.business',
        'image.cats',
        'image.city',
        'image.food',
        'image.nightlife',
        'image.fashion',
        'image.people',
        'image.nature',
        'image.sports',
        'image.technics',
        'image.transport',
        'lorem.word',
        'lorem.words',
        'lorem.sentence',
        'lorem.sentences',
        'lorem.paragraph',
        'lorem.paragraphs',
        'lorem.text',
        'lorem.lines',
        'hacker.abbreviation',
        'hacker.adjective',
        'hacker.noun',
        'hacker.verb',
        'hacker.ingverb',
        'hacker.phrase',
        'internet.avatar',
        'internet.email',
        'internet.userName',
        'internet.protocol',
        'internet.url',
        'internet.domainName',
        'internet.domainSuffix',
        'internet.domainWord',
        'internet.ip',
        'internet.userAgent',
        'internet.color',
        'internet.mac',
        'internet.password',
        'phone.phoneNumber',
        'phone.phoneNumberFormat',
        'phone.phoneFormats',
        'date.past',
        'date.future',
        'date.between',
        'date.recent',
        'date.month',
        'date.weekday',
        'commerce.color',
        'commerce.department',
        'commerce.productName',
        'commerce.price',
        'commerce.productAdjective',
        'commerce.productMaterial',
        'commerce.product',
        'system.fileName',
        'system.commonFileName',
        'system.mimeType',
        'system.commonFileType',
        'system.commonFileExt',
        'system.fileType',
        'system.fileExt',
        'system.directoryPath',
        'system.filePath' ] },
  modules: 
   { type: 'string',
     enum: 
      [ 'fake',
        'random',
        'helpers',
        'name',
        'address',
        'company',
        'finance',
        'image',
        'lorem',
        'hacker',
        'internet',
        'phone',
        'date',
        'commerce',
        'system' ] },
  methodSchemas: 
   { 'random.number': { properties: { options: { type: 'any' } } },
     'random.arrayElement': { properties: { array: { type: 'any' } } },
     'random.objectElement': { properties: { object: { type: 'any' }, ' field': { type: 'any' } } },
     'random.uuid': {},
     'random.boolean': {},
     'random.word': { properties: { type: { type: 'any' } } },
     'random.words': { properties: { count: { type: 'any' } } },
     'random.image': {},
     'helpers.randomize': { properties: { array: { type: 'any' } } },
     'helpers.slugify': { properties: { string: { type: 'any' } } },
     'helpers.replaceSymbolWithNumber': { properties: { string: { type: 'any' }, ' symbol': { type: 'any' } } },
     'helpers.replaceSymbols': { properties: { string: { type: 'any' } } },
     'helpers.shuffle': { properties: { o: { type: 'any' } } },
     'helpers.mustache': { properties: { str: { type: 'any' }, ' data': { type: 'any' } } },
     'helpers.createCard': {},
     'helpers.contextualCard': {},
     'helpers.userCard': {},
     'helpers.createTransaction': {},
     'name.firstName': { properties: { gender: { type: 'any' } } },
     'name.lastName': { properties: { gender: { type: 'any' } } },
     'name.findName': 
      { properties: 
         { firstName: { type: 'any' },
           ' lastName': { type: 'any' },
           ' gender': { type: 'any' } } },
     'name.jobTitle': {},
     'name.prefix': { properties: { gender: { type: 'any' } } },
     'name.suffix': {},
     'name.title': {},
     'name.jobDescriptor': {},
     'name.jobArea': {},
     'name.jobType': {},
     'address.zipCode': { properties: { format: { type: 'any' } } },
     'address.city': { properties: { format: { type: 'any' } } },
     'address.cityPrefix': {},
     'address.citySuffix': {},
     'address.streetName': {},
     'address.streetAddress': { properties: { useFullAddress: { type: 'any' } } },
     'address.streetSuffix': {},
     'address.streetPrefix': {},
     'address.secondaryAddress': {},
     'address.county': {},
     'address.country': {},
     'address.countryCode': {},
     'address.state': { properties: { useAbbr: { type: 'any' } } },
     'address.stateAbbr': {},
     'address.latitude': {},
     'address.longitude': {},
     'company.suffixes': {},
     'company.companyName': { properties: { format: { type: 'any' } } },
     'company.companySuffix': {},
     'company.catchPhrase': {},
     'company.bs': {},
     'company.catchPhraseAdjective': {},
     'company.catchPhraseDescriptor': {},
     'company.catchPhraseNoun': {},
     'company.bsAdjective': {},
     'company.bsBuzz': {},
     'company.bsNoun': {},
     'finance.account': { properties: { length: { type: 'any' } } },
     'finance.accountName': {},
     'finance.mask': 
      { properties: 
         { length: { type: 'any' },
           ' parens': { type: 'any' },
           ' elipsis': { type: 'any' } } },
     'finance.amount': 
      { properties: 
         { min: { type: 'any' },
           ' max': { type: 'any' },
           ' dec': { type: 'any' },
           ' symbol': { type: 'any' } } },
     'finance.transactionType': {},
     'finance.currencyCode': {},
     'finance.currencyName': {},
     'finance.currencySymbol': {},
     'image.image': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.avatar': {},
     'image.imageUrl': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' category': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.abstract': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.animals': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.business': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.cats': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.city': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.food': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.nightlife': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.fashion': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.people': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.nature': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.sports': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.technics': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'image.transport': 
      { properties: 
         { width: { type: 'any' },
           ' height': { type: 'any' },
           ' randomize': { type: 'any' } } },
     'lorem.word': { properties: { num: { type: 'any' } } },
     'lorem.words': { properties: { num: { type: 'any' } } },
     'lorem.sentence': { properties: { wordCount: { type: 'any' }, ' range': { type: 'any' } } },
     'lorem.sentences': 
      { properties: 
         { sentenceCount: { type: 'any' },
           ' separator': { type: 'any' } } },
     'lorem.paragraph': { properties: { sentenceCount: { type: 'any' } } },
     'lorem.paragraphs': 
      { properties: 
         { paragraphCount: { type: 'any' },
           ' separator': { type: 'any' } } },
     'lorem.text': { properties: { times: { type: 'any' } } },
     'lorem.lines': { properties: { lineCount: { type: 'any' } } },
     'hacker.abbreviation': {},
     'hacker.adjective': {},
     'hacker.noun': {},
     'hacker.verb': {},
     'hacker.ingverb': {},
     'hacker.phrase': {},
     'internet.avatar': 
      { description: 'Generates a URL for an avatar.',
        sampleResults: [ 'https://s3.amazonaws.com/uifaces/faces/twitter/igorgarybaldi/128.jpg' ] },
     'internet.email': 
      { description: 'Generates a valid email address based on optional input criteria',
        sampleResults: [ 'foo.bar@gmail.com' ],
        properties: 
         { firstName: 
            { type: 'string',
              required: false,
              description: 'The first name of the user' },
           lastName: 
            { type: 'string',
              required: false,
              description: 'The last name of the user' },
           provider: 
            { type: 'string',
              required: false,
              description: 'The domain of the user' } } },
     'internet.userName': 
      { description: 'Generates a username based on one of several patterns. The pattern is chosen randomly.',
        sampleResults: 
         [ 'Kirstin39',
           'Kirstin.Smith',
           'Kirstin.Smith39',
           'KirstinSmith',
           'KirstinSmith39' ],
        properties: 
         { firstName: 
            { type: 'string',
              required: false,
              description: 'The first name of the user' },
           lastName: 
            { type: 'string',
              required: false,
              description: 'The last name of the user' } } },
     'internet.protocol': 
      { description: 'Randomly generates http or https',
        sampleResults: [ 'https', 'http' ] },
     'internet.url': 
      { description: 'Generates a random URL. The URL could be secure or insecure.',
        sampleResults: [ 'http://rashawn.name', 'https://rashawn.name' ] },
     'internet.domainName': 
      { description: 'Generates a random domain name.',
        sampleResults: [ 'marvin.org' ] },
     'internet.domainSuffix': 
      { description: 'Generates a random domain suffix.',
        sampleResults: [ 'net' ] },
     'internet.domainWord': 
      { description: 'Generates a random domain word.',
        sampleResults: [ 'alyce' ] },
     'internet.ip': 
      { description: 'Generates a random IP.',
        sampleResults: [ '97.238.241.11' ] },
     'internet.userAgent': 
      { description: 'Generates a random user agent.',
        sampleResults: [ 'Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_7_5 rv:6.0; SL) AppleWebKit/532.0.1 (KHTML, like Gecko) Version/7.1.6 Safari/532.0.1' ] },
     'internet.color': 
      { description: 'Generates a random hexadecimal color.',
        sampleResults: [ '#06267f' ],
        properties: 
         { baseRed255: 
            { type: 'number',
              required: false,
              description: 'The red value. Valid values are 0 - 255.' },
           baseGreen255: 
            { type: 'number',
              required: false,
              description: 'The green value. Valid values are 0 - 255.' },
           baseBlue255: 
            { type: 'number',
              required: false,
              description: 'The blue value. Valid values are 0 - 255.' } } },
     'internet.mac': 
      { description: 'Generates a random mac address.',
        sampleResults: [ '78:06:cc:ae:b3:81' ] },
     'internet.password': 
      { description: 'Generates a random password.',
        sampleResults: [ 'AM7zl6Mg', 'susejofe' ],
        properties: 
         { length: 
            { type: 'number',
              required: false,
              description: 'The number of characters in the password.' },
           memorable: 
            { type: 'boolean',
              required: false,
              description: 'Whether a password should be easy to remember.' },
           pattern: 
            { type: 'regex',
              required: false,
              description: 'A regex to match each character of the password against. This parameter will be negated if the memorable setting is turned on.' },
           prefix: 
            { type: 'string',
              required: false,
              description: 'A value to prepend to the generated password. The prefix counts towards the length of the password.' } } },
     'phone.phoneNumber': { properties: { format: { type: 'any' } } },
     'phone.phoneNumberFormat': { properties: { phoneFormatsArrayIndex: { type: 'any' } } },
     'phone.phoneFormats': {},
     'date.past': { properties: { years: { type: 'any' }, ' refDate': { type: 'any' } } },
     'date.future': { properties: { years: { type: 'any' }, ' refDate': { type: 'any' } } },
     'date.between': { properties: { from: { type: 'any' }, ' to': { type: 'any' } } },
     'date.recent': { properties: { days: { type: 'any' } } },
     'date.month': { properties: { options: { type: 'any' } } },
     'date.weekday': { properties: { options: { type: 'any' } } },
     'commerce.color': {},
     'commerce.department': { properties: { max: { type: 'any' }, ' fixedAmount': { type: 'any' } } },
     'commerce.productName': {},
     'commerce.price': 
      { properties: 
         { min: { type: 'any' },
           ' max': { type: 'any' },
           ' dec': { type: 'any' },
           ' symbol': { type: 'any' } } },
     'commerce.productAdjective': {},
     'commerce.productMaterial': {},
     'commerce.product': {},
     'system.fileName': { properties: { ext: { type: 'any' }, ' type': { type: 'any' } } },
     'system.commonFileName': { properties: { ext: { type: 'any' }, ' type': { type: 'any' } } },
     'system.mimeType': {},
     'system.commonFileType': {},
     'system.commonFileExt': { properties: { type: { type: 'any' } } },
     'system.fileType': {},
     'system.fileExt': { properties: { mimeType: { type: 'any' } } },
     'system.directoryPath': {},
     'system.filePath': {} } }
```

**Comment by cliffpyles** [comment]
@Marak That sounds awesome. I'll get the remainder done this week.

**Comment by cliffpyles** [comment]
@Marak address.city allows for one of four formats to be specified, but the format is passed as a number which represents the index of a format, which is contained in an array. It isn't immediately clear how this argument works, unless you dig into the source. Any thoughts on good ways to capture this type of scenario in the schema? Maybe some sort of map for indexes to formats?

**Comment by Marak** [comment]
@cliffpyles -

I suspect improving the uniformity of API calls will come up a few times as we implement schema API contracts for every method.

I would suggest you skip any methods which do not have straight forward API contracts. Make a note of each irregular API call.

Once we have a better idea of what API calls are irregular, we can figure out the best way to provide a uniform API for the entire library.

Since changing an API contract is a breaking change, we'll want to do them all at once and publish a new major version ( v4.0.0 )

**Comment by BenLorantfy** [comment]
A link to the documentation from the Readme would be great. It's not always obvious the documentation is in the wiki.

**Comment by Moosh-be** [comment]
What's missing to close this issue ?
