### ISSUE TITLE
Add options to the format of internet.userName()

### ISSUE THREAD

**Issue by serv** [Marak/faker.js#171]
It would be nice if we allowed passing options to `userName()` that would allow us to generate usernames that just uses `_` or `-` or `.` instead of randomly cycling through all formats.

**Comment by Marak** [comment]
Sounds good!

Will accept pull request for this functionality.

**Comment by serv** [comment]
I'll work on this.

I think creating new methods `userNameUnderscore()`, `userNameDot()` and `userNameHyphen()` are better than updating the current `userName()` method.

It's way easier for people to understand and use the methods, although these methods look repetitive.

**Comment by Truffula** [comment]
I'm not sure if this is too big a departure from the existing API, but for methods that have a number of options (e.g. first name, last name, separator), would it make sense to pass an options object instead of having fixed parameters? e.g: 
```js
fixer.internet.email({
    firstName: 'Bob',
    separator: '.'
});
```

**Comment by Marak** [comment]
I've got a local branch in development that should address this issue as well as #226 #199 and #195

Should have something online in the next day or two.

**Comment by Marak** [comment]
Using `master` branch you should be able to format and combine any existing faker methods.

Examples here: https://github.com/Marak/faker.js/blob/master/examples/generators.js

Sample syntax:

 ```js
console.log(faker.fake('{{name.firstName}}.{{name.lastName}}@{{internet.domainName}}'));
```

I'm thinking this will solve most use cases...let me know.
