### ISSUE TITLE
Faker.random.boolean()

### ISSUE THREAD

**Issue by alanshaw** [Marak/faker.js#176]
I often need this but end up having to write `Faker.random.array_element([true, false])`. Would you welcome a PR?

**Comment by Marak** [comment]
Sounds good!

Will accept pull request for this functionality.

**Comment by alanshaw** [comment]
Weirdness, not sure why that commit didn't make it into the PR - https://github.com/Marak/faker.js/compare/master...alanshaw:random-boolean

**Comment by tkoomzaaskz** [comment]
Maybe it's because travis has failed there: https://travis-ci.org/Marak/faker.js/jobs/57912682 ?

**Comment by soichih** [comment]
I did something like this
> headers.PatientSex = faker.random.number(1)?'M':'F';
Does this do the same thing as .boolean()?
