### ISSUE TITLE
Can't require as Node module

### ISSUE THREAD

**Issue by marnen** [Marak/faker.js#179]
I've got Faker 2.1.2 installed in `node_modules` and in my `package.json` file under `devDependencies`. Yet when I do `require('faker')`, it says `Cannot find module 'faker'`. All other dependencies can be `require`d as expected. Help?

I'm using npm 2.6.1 on Mac OS X 10.10.

**Comment by jlas** [comment]
Does `require('Faker')` work?

**Comment by Marak** [comment]
Sounds like an environment issue?

Try installing the latest version of `npm` and or running `npm cache clean`?

The project should be requirable.

**Comment by marnen** [comment]
Of course I ran `npm install`. :)

**Comment by marnen** [comment]
Of course I ran `npm install`. That's why the module was in `node_modules` in the first place. :)

**Comment by tkoomzaaskz** [comment]
@marnen thank you for the response. And could you repeat the situation and check if everything works now? Could you execute above commands?

**Comment by wang-chenxi** [comment]
Awesome, solved my issue as well
