### ISSUE TITLE
`bs_noun` defined twice in sk.js

### ISSUE THREAD

**Issue by TheSharpieOne** [Marak/faker.js#183]
https://github.com/Marak/faker.js/blob/master/lib/locales/sk.js#L2217 and https://github.com/Marak/faker.js/blob/master/lib/locales/sk.js#L2284

Duplicate data property in object literal not allowed in strict mode

**Comment by tkoomzaaskz** [comment]
The issue doesn't exist anymore, `bs_noun` is defined only once is locale:sk.

**Comment by TheSharpieOne** [comment]
Yeah, it was fixed in #184. Doesn't look like it got linked and auto-closed.
