### ISSUE TITLE
RESTful API?

### ISSUE THREAD

**Issue by levithomason** [Marak/faker.js#189]
What do you think about a REST API?  I can imagine something akin to http://unsplash.it or http://placehold.it for images.  http://faker.it happens to be available.  A simple heroku app could achieve this.  Sounds lie a fun and useful build.

Let me know if you're interested, or especially if this already exists :)

Thanks, love your library.

**Comment by anthonyringoet** [comment]
Reminds me of http://reqr.es/

**Comment by levithomason** [comment]
Nice, yep.

**Comment by alvaropinot** [comment]
Will not really be the same as http://reqr.es. I would be glad to help make it out :D

**Comment by Marak** [comment]
Sounds good.

If you put something together, it would always be nice to see commits come back to faker.js project or links to the open-source repository.

Let me know!
