### ISSUE TITLE
create fake ID or GUID?

### ISSUE THREAD

**Issue by mromanoff** [Marak/faker.js#192]
it would be nice to have a fake GUID too.

**Comment by snipesjr** [comment]
Like the uuid function in the random module or something different?

**Comment by mromanoff** [comment]
i this uuid will do for me. but i had no clue it is exists. please update documents :-)

**Comment by Marak** [comment]
Pull request will be accepted to update documentation.

**Comment by tkoomzaaskz** [comment]
The docs have been updated, so this issue gets closed.
