### ISSUE TITLE
extending faker with custom generators

### ISSUE THREAD

**Issue by ducin** [Marak/faker.js#199]
I'm using faker.js and I started to need my custom generators that would reuse original faker generators. Does faker provide such feature? I know I can assign custom attribute functions to pre-loaded faker object, but I'm not sure whether it's the best solution (e.g. not sure whether it's gonna work with locales and other features).

I was thinking of sth like [_.mixin](http://underscorejs.org/#mixin). If you find it useful, please let me know.

**Comment by tkoomzaaskz** [comment]
Update:

chance.js, a similar library, already has such functionality: https://github.com/victorquinn/chancejs/issues/178

**Comment by Marak** [comment]
This can be done with a few lines of JavaScript, it's not really something specific to faker.

If you want to add a mixin connivence method to the API with a pull request, I will probably merge it.

**Comment by Marak** [comment]
Customer generators are now landed in `master`.

Examples here: https://github.com/Marak/faker.js/blob/master/examples/generators.js
