### ISSUE TITLE
upcoming v2.1.4 release

### ISSUE THREAD

**Issue by ducin** [Marak/faker.js#210]
I'd like to discuss the contents of the next upcoming release in this thread. I thought it's high time to include locales which have been prepared by few guys, who put **great effort** into it. This would include:
* traditional Chinese: #178
* Turkish: #181
* Georgian: #158
 
Smaller changes:
* readme: require node module #129

**Comment by Marak** [comment]
I'd recommend performing issue triage to determine if there are any bugs that should be fixed.

Merging in the locales work also sounds great.

1. Fix bugs
2. Add new locales

**Comment by tkoomzaaskz** [comment]
@Marak you're right. Also I try to make a release including commits from similar background (locales, docs, etc). Also, there is some important stuff that needs lots of work and I can't do it soon. And I can prepare a bunch of small commits. But generally I agree with you and I'll try to do my best!

Do you know about heart-bleeding bugs?

**Comment by Marak** [comment]
I don't think there are.

Only way to find out is to triage all open issues.

:-)

**Comment by tkoomzaaskz** [comment]
Ok, so I'm triaging open issues.

Meanwhile, I think we coudl remove branch [v2.1.3](https://github.com/Marak/faker.js/tree/v2.1.3) because it has been already both merged and published. Ok for me to do it?

**Comment by tkoomzaaskz** [comment]
I've created [`v2.1.4`](https://github.com/Marak/faker.js/tree/v2.1.4) branch. Currently there are 3 minor commits:
* updated #129 
* devDependency badge in readme
* devDependencies updated. These were really outdated!

All the commits contain source changes only (to make easy cherry-picks). The last commit contains build & version bump. If we extend `v2.1.4`, I'd remove the last commit (to make the history cleaner).

**Comment by sethkinast** [comment]
Please update `bower.json`'s version when you push the next release-- it's still stuck at 2.0.0.

**Comment by Marak** [comment]
@tkoomzaaskz - Please resolve #213 and we can call it a release. We will also need a basic test suite for `locales`.

Thanks! :-)

**Comment by Marak** [comment]
@tkoomzaaskz -

#159 needs to be included in the release as well. There are few other issues related to this. Please fix ASAP.

**Comment by Marak** [comment]
`v2.1.4` and `v2.1.5` are now released.
