### ISSUE TITLE
`random.number` negative values issue

### ISSUE THREAD

**Issue by pateketrueke** [Marak/faker.js#216]
I have the following code:

```js
var faker = require('faker');

console.log(faker.random.number({ min: -100, max: 0 })); // FAIL
console.log(faker.random.number({ min: -100, max: 1 })); // OK
```

Faker fails on generate negative numbers with those options.

It is a known issue?

**Comment by philberg** [comment]
I have fixed this issue in [my PR](https://github.com/Marak/faker.js/pull/218) and added an explicit test

**Comment by Marak** [comment]
This should be resolved now.
