### ISSUE TITLE
Use locale's name format for findName

### ISSUE THREAD

**Issue by nephridium** [Marak/faker.js#220]
Names not formatting correctly for certain locales. Looks like this is part of issue #133, but i decided to pull the findName() part into a separate issue since I have a fix at least for that one.

Got rid of the randomized generic formatting and instead use a newly minted helpers.template() function which works like mustache() but for the `#{}` marker that is currently used for the name string interpolation (might want to consolidate those two in the future.)

Also added a middleName() function and modified firstName() and lastName() to get "ru" locale working #213. 

Added unit tests for helpers.template() and mustache().

You can see the fix at https://github.com/nephridium/faker.js/tree/nameformat; tests are succesfull (except for coverage issue in current master), so if you're ok with it I could do a PR?

**Comment by nephridium** [comment]
Any input on this issue? Is there something I need to improve in my fix?

**Comment by Marak** [comment]
If you have a change make a PR and I will review it.

This request for review is out-of-band of the PR process.
