### ISSUE TITLE
FR: add fake location generator following given location path (GPS track)

### ISSUE THREAD

**Issue by afanasy** [Marak/faker.js#222]

**Comment by Marak** [comment]
@afanasy 

That sounds nice.

We could probably do it with a simple local look-up table and some approximation.

Will accept a pull request or even just a basic implementation.

Thanks!

**Comment by afanasy** [comment]
@Marak thanks! Didn't have time to adopt my implementation for the faker
lib, but it's in my todo list!

**Comment by Marak** [comment]
Should be resolved with #378

Closing.
