### ISSUE TITLE
Remove \t tab from lorem.paragraphs

### ISSUE THREAD

**Issue by justrhysism** [Marak/faker.js#223]
The `\t` tab on [Line 40 of lorem.js](https://github.com/Marak/faker.js/blob/master/lib/lorem.js#L40): 

```javascript
return paragraphs.join("\n \r\t");
```

is unnecessary and causes issues when using faker to generate markdown (_not to mention old school, you're not supposed to indent new paragraphs anymore - unless you're publishing print_).

Could it please be removed.

```javascript
return paragraphs.join("\n \r");
```

**Comment by Marak** [comment]
It seems like this should be an option. Some people might want the paragraphs to return with indents.

If you want to open up a pull request to change this I will accept.

This function https://github.com/Marak/faker.js/blob/master/lib/lorem.js#L34 should accept an additional parameter for for formatting where `\n \r\t` is the default.

**Comment by kovpack** [comment]
@Marak: `\n \r\t` definitely should not be the default value. Default value is always the one that is most common, so I completely agree with @justrhysism .

Tabs are extremely **uncommon** (this is the first place I see it during last few years). That means that when 99% of users call the function they should not pass extra params. If 1% of users want to use something uncommon - they should pass extra param. That seems to be a good practice.

**Comment by Marak** [comment]
Okay. So change the default to that.

Still needs to be configurable. Make the PR.

**Comment by Marak** [comment]
I have updated API to not use `\t` by default. The separator for joining paragraphs is also now configurable.

Thank you for the feedback.
