### ISSUE TITLE
companyName format can't be forced to type 0

### ISSUE THREAD

**Issue by Truffula** [Marak/faker.js#226]
If you pass 0 to `companyName`, it still fetches a random number (I haven't checked if other functions are affected).

```js
    companyName: function (format) {
        switch ((format ? format : faker.random.number(2))) {
        case 0:
            return faker.name.lastName() + " " + faker.company.companySuffix();
        case 1:
            return faker.name.lastName() + "-" + faker.name.lastName();
        case 2:
            return faker.name.lastName() + ", " + faker.name.lastName() + " and " + faker.name.lastName();
        }
    },
```
Fixed:
```js
    companyName: function (format) {
        switch ((typeof format === "number" ? format : faker.random.number(2))) {
        case 0:
            return faker.name.lastName() + " " + faker.company.companySuffix();
        case 1:
            return faker.name.lastName() + "-" + faker.name.lastName();
        case 2:
            return faker.name.lastName() + ", " + faker.name.lastName() + " and " + faker.name.lastName();
        }
    },
```

**Comment by Marak** [comment]
We should really remove all of these string concats and arbitrary numbers and replace them with a format string / custom generator.

see: #199 #195

**Comment by Marak** [comment]
@Truffula - Good catch. 

I'm just going to remove all the switch / case logic entirely. Using a format string / allowing custom generators will make the whole API easier to use.

**Comment by Marak** [comment]
@Truffula - I should have this fixed now in `master`. I will review the rest of the code-base for similar errors to this.

With the new `faker.fake` generator method, we can remove a lot of this logic and make the code more simple.

Thanks for the feedback!

**Comment by Truffula** [comment]
Cheers!
