### ISSUE TITLE
Faking random file names, paths, extensions and content types

### ISSUE THREAD

**Issue by hellboy81** [Marak/faker.js#228]
Is there possible to implement this feature?

**Comment by Marak** [comment]
You could generate file names, paths, extensions, and content types pretty easily. This would require mime type lookup table. https://github.com/broofa/node-mime/blob/master/types.json

Why is it you need this functionality? What's the purpose?

**Comment by hellboy81** [comment]
In unit tests I should use insted of  `image03.jpg`, `image01.png`, `iamge02.gif` random generated file names

**Comment by Marak** [comment]
Closing issue.

This should be resolved in `master`.

Please feel free to add more information if you feel we should revisit this.
