### ISSUE TITLE
Update to latest version on CDNs

### ISSUE THREAD

**Issue by someatoms** [Marak/faker.js#229]
Would be nice to have the latest version on [cdnjs](https://cdnjs.com/libraries/Faker) and [jsDelivr](http://www.jsdelivr.com/#!faker.js). Right now they have 0.7.* versions.

**Comment by Marak** [comment]
Okay.

When the next version of faker is released I will update cdnjs and jsDelivr.

If you want to put up the current version now, please feel free.

**Comment by someatoms** [comment]
Awesome!

**Comment by jimaek** [comment]
I enabled auto-updates for faker.js. Our bot will now automatically upload new versions once they get tagger in Github.
The last version is now live http://www.jsdelivr.com/#!faker.js

**Comment by someatoms** [comment]
Awesome!
