### ISSUE TITLE
add MX locale

### ISSUE THREAD

**Issue by isortegah** [Marak/faker.js#231]
I would like to add a library of definitions for mexico

**Comment by Marak** [comment]
Sounds good. Will accept a PR.

**Comment by isortegah** [comment]
I can not find how to make the pull request

**Comment by Marak** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by Marak** [comment]
Data goes here: https://github.com/Marak/faker.js/tree/master/lib/locales

You can look at the other locales to see how the format is.

If you can add the data, I can figure out the rest.

**Comment by Marak** [comment]
Merged with https://github.com/Marak/faker.js/pull/238

Closing.
