### ISSUE TITLE
"lorem" improvements

### ISSUE THREAD

**Issue by SimonDegraeve** [Marak/faker.js#233]
Hi,

I was wondering if there is any reason why `lorem.sentence` is not capitalize and does not end with a dot?

> [...] In print or writing, a sentence typically begins with a capital letter and ends with appropriate punctuation.

Also I think it is a bit inconsistent to have `lorem.words` returning an `Array` but `lorem.sentences` and `lorem.paragraphs` returning a `String`.

I notice we can now choose the `separator` for `lorem.paragraphs`. I think the default should not have a `tab`, it is more common.

Regards

**Comment by Aweary** [comment]
I definitely agree. A lexical sentence should start with a capital letter and end with a period. Any return value that is a plural should return an array like words does as well, for consistency. I'll get a PR going for this.

**Comment by Marak** [comment]
Related Issue #223

**Comment by Marak** [comment]
@SimonDegraeve - There is some previous discussion on this issue #223.

Will accept a PR for updating the `lorem` generators if there are improvements to be made.

**Comment by Aweary** [comment]
I think changing the sentence format is an easy win, and have a PR incoming, but the only concern I have is that changing the return type of `lorem.sentences` and `lorem.paragraphs` is going to be potentially be a breaking change for some users. It does make more sense, and would be consistent, though.

**Comment by pho3nixf1re** [comment]
See my PR above making the words method return a string.

**Comment by Marak** [comment]
Lorem has been improved in latest `v.3.1.0` release.
