### ISSUE TITLE
FR: Allow specification of a seed value

### ISSUE THREAD

**Issue by VanTanev** [Marak/faker.js#239]
It would be nice if we could get deterministic output from Faker. It seems that the lib used for random generation already supports this (https://github.com/Marak/faker.js/blob/master/vendor/mersenne.js#L273), so it's just a matter of exposing this interface somewhere on Faker.

**Comment by Marak** [comment]
Sounds good. Will accept a PR.

**Comment by Marak** [comment]
Should be fixed in `master`.

Thanks @Aweary !
