### ISSUE TITLE
faker.internet.email() should probably only return lowercase characters

### ISSUE THREAD

**Issue by VanTanev** [Marak/faker.js#240]
As it stands, most email providers (actually, all that I am aware of) convert emails to all-lowercase. This means that, if we generate data with faker and then use it for, say, an integration test that verifies new user registrations, we get a mismatch between the data generated from Faker and the new user's email.

**Comment by Marak** [comment]
That sounds pretty reasonable, although I'm not sure.

Could you simply just call `String.toLowerCase()` on the output of the fake email address method in your application?

I'm hesitant to take away uniqueness of a generated piece of data unless there is a compelling reason.

If anyone else has input on this please let us know.

**Comment by VanTanev** [comment]
Yeah, it's what I'm currently doing. Worth mentioning that the gem version seems to already be doing this - https://github.com/stympy/faker/blob/master/lib/faker/internet.rb#L5-L46 - going as far as to only generate lowercase usernames.

**Comment by Aweary** [comment]
Since it's a really simple fix to just use `String.toLowerCase()` when you need to, I'd say it's best to preserve the uniqueness. This way, people who *do* want uppercase letters can still use them, and people who don't can easily fix that.

**Comment by sethkinast** [comment]
I agree; you want faker to simulate real data entry, and lots of people will enter their email address as FirstNameLastName@MyDomain.com or similar.

**Comment by VanTanev** [comment]
I would like to point out that converting emails to lowercase actually **does not** lower the uniqueness of generated data. Since there is no randomness to the generated case of names to begin with (they always start with an upper case, and an uppercase cannot show at a random position in the name), using a lowercase representation doesn't modify the number of possible combinations.

My only reason for proposing this change is that in reality, any service will convert an email to lowercase only before use. Returning mixed-case results from faker breaks faker's implicit contract - that it generates real-world-like data. Even if users *could* enter mixed-case emails (and indeed, mixed case is valid in emails), the actual canonical representation will always be lowercase.

Still, if the majority doesn't agree with this proposition, then by all means, keep the current implementation. 

Thanks for your time :)

**Comment by Aweary** [comment]
> My only reason for proposing this change is that in reality, any service will convert an email to lowercase only before use. 

I agree, and thats why I think it's important to keep them as-is. Changing the case of the input would be part of the system being tested with Faker, so it's more realistic to provide data that is close to what the user would input, which leaves it up to the developer to implement those canonical representations.

 As an extreme example, we all know that any good system is going to hash passwords before storing them, but that doesn't mean we should be hashing them in Faker.

**Comment by VanTanev** [comment]
I can see your reasoning. Fair enough, closing this. 
Thanks again :)
