### ISSUE TITLE
Uncaught TypeError: result.replace is not a function when setting faker.internet.email

### ISSUE THREAD

**Issue by vitasiku** [Marak/faker.js#241]
I am getting the following error in the chrome console which stops my ember-cli app from running

    `internet.userName @ faker.js:722
    internet.email @ faker.js:704
    (anonymous function) @ factory.js:14
    Factory.build @ factory.js:10
    exports.default.create @ server.js:132
    exports.default.createList @ server.js:140
    exports.default @ default.js:8
    exports.default.initialize @ 
    ember-cli-mirage.js:34
    (anonymous function) @ 
    ember.debug.js:4316
    (anonymous function) @ ember.debug.js:4340
    ...
    and some other lines here`

Am am using faker@2.1.5 with ember-cli-mirage
Looking into the source code at the line fake.js:722, the highlighted line is where the error occurs
....
```result = result.replace(/'/g, ""); ```  
result = result.replace(/ /g, "");
return result;

**Comment by Marak** [comment]
Can you try upgrading to `v3.0.0` ?

**Comment by Marak** [comment]
Can you also link to the actual line number on Github?

**Comment by Marak** [comment]
I find that line, it should always have a value and should have test coverage.

https://github.com/Marak/faker.js/blob/master/lib/internet.js#L31

I would try going into the source code and dropping a debug statement to find out why result isn't being set. Could be an issue with your environment, not really sure.

**Comment by vitasiku** [comment]
Updating to ```v3.0.0``` fixed the problem. 
Thanks.
