### ISSUE TITLE
Throw an error when Locale missing

### ISSUE THREAD

**Issue by kbariotis** [Marak/faker.js#247]
This [check](https://github.com/Marak/faker.js/blob/master/lib/index.js#L112) will yield an unhandled TypeError if the Locale that has been setted is missing or can't be found. It should handle it by throwing an error.

**Comment by Marak** [comment]
There is general issue now with grouping of locales and locale fallbacks.

Locales should be grouped by language with a primary language the a sub-locale. For example:

**Main locale**
`en`

**Sub-locales**
`en_AU`, `en_BORK`, `en_CA`, `en_GB`, `en_IE`, `en_IND`, `en_US`, `en_au_ocker`

The idea is that if a definition is not found in the sub-locale, the main locale is used as a fallback.

@kbariotis - The best thing to do for now would probably be to ensure the API doesn't crash with a type error. We'll have to figure out a better solution moving forward for locale fallbacks.

**Comment by kbariotis** [comment]
I see your point. In my case there is no sub locale. There is only one. Where should the actual data go? To the mail locale or create a sub locale and put them there?

Also, a suggestion here would be to, besides each locale's fallback, to exist a global default locale that every locale should fall into. Particularly, I suggest `en` to be that fallback. This way even if some data are missing from the requested locale, provide English data and not throw an error.

**Comment by Marak** [comment]
I agree @kbariotis . `en` is probably the best default fallback.

If you have a solution please open up a PR. If not, I can try to sort out a solution in the next weeks.
