### ISSUE TITLE
Release to Bower

### ISSUE THREAD

**Issue by chadhietala** [Marak/faker.js#249]
Would you mind releasing a version to Bower that has the locale specific built files.

Thanks

**Comment by Marak** [comment]
I don't mind at all, but I'm not exactly sure how to do that as I've never really used Bower.

The package manifest for Bower can be found here: https://github.com/Marak/faker.js/blob/master/bower.json

To my understand, there is no publish step required. Having a properly formatted manifest should be the only requirement.

**Comment by chadhietala** [comment]
Sorry wrong project.. There is a Faker and faker

**Comment by Marak** [comment]
Could you elaborate on what you did to fix the problem? 

Other Bower users might end up here.
