### ISSUE TITLE
Arabic local support

### ISSUE THREAD

**Issue by samirgit** [Marak/faker.js#257]
are you planning by any chance to add arabic language support? i am new to faker and so far loving this tool. but now i'm working on an arabic application so need that arabic support! thank you

**Comment by Marak** [comment]
I don't speak Arabic, so I won't be adding it myself.

If anyone else wants to add Arabic ( or any other locale ) I will accept a PR.

**Comment by Marak** [comment]
@samirgit 

Any luck with this?

Adding a new locale is pretty easy! All you have to do is copy an existing one and start changing the data. Everything else is automatic.

**Comment by alnour-altegani** [comment]
hi @Marak I started to add arabic locale . when I finish the translation i will send a pull request .
@samirgit can you help ?

**Comment by Marak** [comment]
@samirgit - We should now have an `ar` locale.

Please feel free to review it.
