### ISSUE TITLE
Npm install Faker fails.

### ISSUE THREAD

**Issue by gnetsys** [Marak/faker.js#259]
Error on faker install.
 
npm ERR! Expected: ee9f7a3f40c15f68b9402088aa8f18a0ce4da00e
npm ERR! Actual:   0fc988492dd59038ee35fb29a43a5f2171bd2a9f

**Comment by Marak** [comment]
Try updating your `npm`?

`sudo npm install npm -g`

**Comment by Marak** [comment]
Did that work?
