### ISSUE TITLE
Smallest bundle possible for English

### ISSUE THREAD

**Issue by whitlockjc** [Marak/faker.js#264]
Right now I'm using [json-schema-faker](https://github.com/pateketrueke/json-schema-faker) which uses faker.js.  Whenever I use browserify to bundle my package, it's including 842 files related to faker.js locales out of a total of 947 files.  Since all of my error messages are English and I've no immediate need for localization, I'd love to figure out the best way to make the smallest faker.js footprint.  Your documentation says I can do something like this `require('faker/locale/en')` but does `en` include `en` and `en_*`?  If so, could I use `require('faker/locale/en_US')` to get only the US English locale to get the smallest faker.js footprint?

**Comment by whitlockjc** [comment]
I wanted to label this a `question` but I cannot.  I'm currently seeing if I can find the answer via source surfing.  If I figure it out before I get a response, I'll update this issue.

**Comment by whitlockjc** [comment]
I figured it out.  :)  It seems that `en_US` is what I want and it will include all of `en` to `en_US`.  `en` would probably be fine but it seems `en_US` updates some things to be more US specific.

**Comment by Marak** [comment]
Thanks @whitlockjc 

Please let us know if you have any other questions.
