### ISSUE TITLE
es_MX local is littered with non-breaking spaces

### ISSUE THREAD

**Issue by whitlockjc** [Marak/faker.js#267]
The `es_MX` local is littered with non-breaking spaces `\xA0` in place of regular spaces.  Node.js handles this without issue as it assumes UTF-8 file encoding but for the browser, without explicitly using the `charset` attribute to specify `UTF-8` in the script tag, you will end up with an `Unexpected identifier` error.  A good example is `lib/locales/es_MX/commerce/color.js`.  If I build that local into my sources using Browserify, I get the aforementioned error.  Here is what the inspector shows for the source for `color.js`:

```js
// ...
Â Â  "verde",
Â Â  "azul",
Â Â  "amarillo",
// ...
```

As you can see the `\xA0`, represented here with the `Â`, causes the JavaScript interpreter to freak out.  Of course, I can change my script tag from `<script "myscript.js"></script>` to `<script "myscript.js" charset="UTF-8"></script>` to fix this but should I have to?  Here is a list of all files that are impacted by this, including build artifacts:

```
find . -name "build" -prune -o -name "examples" -prune -o -name "*.js" -exec grep -cH " " '{}' \; | grep -v ":0"
/build/build/faker.js:336
./build/build/locales/es_MX/faker.es_MX.js:336
./examples/browser/js/faker.js:336
./examples/browser/locales/es_MX/faker.es_MX.js:336
./lib/locales/es_MX/commerce/color.js:30
./lib/locales/es_MX/commerce/department.js:21
./lib/locales/es_MX/commerce/product_name.js:53
./lib/locales/es_MX/company/bs_adjective.js:64
./lib/locales/es_MX/company/bs_noun.js:43
./lib/locales/es_MX/company/bs_verb.js:59
./lib/locales/es_MX/team/creature.js:66
```

This is an easy fix but I don't want to do the work if you don't think this is important.

**Comment by Marak** [comment]
cc @sortegah

**Comment by Marak** [comment]
cc @isortegah

**Comment by Marak** [comment]
@whitlockjc - Sounds like the person who did that locale might have a weird setting in their editor.

Could you do a search and replace to fix this?

**Comment by whitlockjc** [comment]
You can.  I can send you a PR if you'd like but as I mentioned earlier, before dropping a PR on you I wanted to see if it was something you wanted.  I'll assume that's the case unless I hear otherwise.

**Comment by Marak** [comment]
PR would be great, thanks!

**Comment by whitlockjc** [comment]
Should I only update the files in `lib`?  I see some characters in `build` and `examples` too but if they are build artifacts at release time, I don't want to muck with those unless you want me to.

**Comment by whitlockjc** [comment]
I have everything ready, tests running, for `lib`.  Just let me know about `build` and `examples` and we'll go from there.

**Comment by Marak** [comment]
Don't worry about the builds. We only do those for releases.

**Comment by whitlockjc** [comment]
Done.  I ran tests and got some coverage error but since I didn't touch any tests, I don't think this is related to my changes.

**Comment by Marak** [comment]
Cool, thanks! 

We use Travis to determine correctness of tests.

https://travis-ci.org/Marak/faker.js

Looks like its passing. I will pull later and check locally before release.
