### ISSUE TITLE
Migration from 2.x to 3.x

### ISSUE THREAD

**Issue by kimmobrunfeldt** [Marak/faker.js#280]
Could you include all breaking API changes to [CHANGELOG.md](https://github.com/Marak/faker.js/blob/20ec97b9b7449ba0ca37a90226a8651f18164e53/CHANGELOG.md) ?

> See commit history on Github for change history http://github.com/marak/faker.js

It's quite a big of a task to go through all individual commits and their diffs after 2.x release.

**Comment by Marak** [comment]
@kimmobrunfeldt -

I'd like to, but my time constraints don't really allow it.

I try to take care with the git commit messages so they form a story about what is the CHANGELOG.

Maybe you could make a tool that parses commit messages based on our tag styles which generates a CHANGELOG automatically?

**Comment by kimmobrunfeldt** [comment]
It's definitely possible and I could do something like that to help this project, but there are a few problems in my opinion:

* The commit messages don't seem to follow the convention that strictly
* Bigger issue: how would automatic tool detect library public API changes? That's the most important information for the users like me. If I update the library, which methods do I need to change etc. In my experience, that requires manual work. The manual work doesn't take that long for the core maintainers since they have good knowledge of the previous APIs.

**Comment by Marak** [comment]
Yeah, I dunno.

It's a lot of work to do.

If you could help get us up to date today, I can commit to updating in the future.

**Comment by kimmobrunfeldt** [comment]
I'll put it on my todo list and get back to it later. Might take some time. Is the README.md's API documentation up to date? I can do a comparison of the README.md between 2.x and 3.x versions.

**Comment by Marak** [comment]
Do whatever you can do.

Thank you for your contribution!

**Comment by Marak** [comment]
As discussed, I'm keeping a CHANGELOG of the next round of changes coming for the release.

If you could help provide any back-data to add from previous version, that would help.
