### ISSUE TITLE
it should be able to generate random bitcoin addresses

### ISSUE THREAD

**Issue by gberger** [Marak/faker.js#285]
A Bitcoin address, or simply address, is an identifier of 27-34 alphanumeric characters, beginning with the number 1 or 3, that represents a possible destination for a Bitcoin payment.

**Comment by Marak** [comment]
@gberger 

Sounds good.

A pull request would be welcomed.

**Comment by Marak** [comment]
Or it could just return from a pool of my addresses every-time. I'm also good with that.

**Comment by Marak** [comment]
@gberger -

I'm not sure bitcoin address generation is that simple.

Have you actually tried generating "fake" bitcoin addresses using this technique and checking them against the blockchain?

**Comment by Marak** [comment]
#359

**Comment by paolodm** [comment]
This issue seems closable since Bitcoin support was implemented in #352. If you agree, please close it.

**Comment by johnmaia** [comment]
I've submitted a PR (#591) a few days ago to fix the current version of the `bitcoinAddress` generator.

**Comment by Marak** [comment]
Can someone please look into the Bitcoin address generation. It seems to have broken with #591 

Any help would be appreciated.

**Comment by Marak** [comment]
This should be resolved in `master`.

Thank you for your contributions and feedback.

Closing.
