### ISSUE TITLE
Prepare 3.1.0 Release

### ISSUE THREAD

**Issue by Marak** [Marak/faker.js#287]
It's about getting time to do a new release.

I'll triage the issues in the next week to prioritize what will be included.

If anyone has any additional issues or comments on the next release please post them here.

**Comment by lmcardle** [comment]
Semi-related, master appears, at least the docs, to be behind the 3.0.1 release. the docs still are using a number of snake case method names (i.e. array_element) where 3.0.1 readme uses camel case (i.e. arrayElement). For documentation, it would be helpful if the current release readme matched master.

**Comment by Marak** [comment]
Going to bump to `v3.1.0`

`master` is prepped for release, we also have JSdocs up at http://marak.github.io/faker.js/

Should release tomorrow.

**Comment by Marak** [comment]
Was released a few weeks ago.

Cheers!
