### ISSUE TITLE
[question] [discussion] [help needed] Generating MongoIDs etc...

### ISSUE THREAD

**Issue by hellboy81** [Marak/faker.js#306]
With [`chance.js`]() I can generate random upper-cased string IDs (such as `MongoID`) with [`chance.hash`](http://chancejs.com/#hash) :

```js
// json-schema-faker fragment:
chance: {
  hash: {
    casing: 'upper',
    length: 32
  }
}
```

What is the best way to generate such values in `faker.js`?

**Comment by Marak** [comment]
`faker.random.uuid()` should work

**Comment by Marak** [comment]
#359
