### ISSUE TITLE
faker.seed() does not return predictable words from faker.lorem

### ISSUE THREAD

**Issue by pillowfication** [Marak/faker.js#309]
faker.seed(555);
    var word1 = faker.lorem.words(1)[0]; // word1 = 'maiores'
    faker.seed(555);
    var word2 = faker.lorem.words(1)[0]; // word2 = 'quae'
    
    word1 == word2; // false

This is because faker is shuffling definitions.lorem.words and not restoring its original state upon setting the seed.

**Comment by Marak** [comment]
Can you open a PR for this?

**Comment by Marak** [comment]
Fixed in MASTER with https://github.com/Marak/faker.js/commit/d2a70d71817e2b4e1062a0bc777933705bf1c626
