### ISSUE TITLE
support for square imagery

### ISSUE THREAD

**Issue by corysimmons** [Marak/faker.js#312]
plz?

**Comment by Marak** [comment]
I'll need more details for this.

I believe the random image methods provide a height and width parameter...so that should be able to return a square?

You tell me.

**Comment by corysimmons** [comment]
I don't think it accepts any params? It's not documented anywhere anyway

http://codepen.io/corysimmons/pen/GoYbRK?editors=0010

**Comment by Marak** [comment]
Hrmm.

Is seems to be there?
https://github.com/Marak/faker.js/blob/master/lib/image.js#L5

Maybe only in master?

**Comment by corysimmons** [comment]
Hmm, `faker.image.imageUrl(500, 500)` works but not `faker.image.image(500, 500)`.

Do you think you could add documentation for the options associated with each method?

**Comment by Marak** [comment]
I'll double check the image API before the next release.

Documentation is being worked on at #170 

Thanks for the bug report.

**Comment by corysimmons** [comment]
Cool, thanks for the cool tool. =)
