### ISSUE TITLE
Invalid date of birth

### ISSUE THREAD

**Issue by yzkee** [Marak/faker.js#328]
Month 0 was generated 
![dob](https://cloud.githubusercontent.com/assets/5499985/12047413/edf15b74-af05-11e5-8efc-ba3779920ee0.PNG)

**Comment by jory** [comment]
That's actually valid, see [Date.getMonth()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth).

> The getMonth() method returns the month in the specified date according to local time, as a __zero-based value (where zero indicates the first month of the year)__.

**Comment by natzar** [comment]
Valid as date for computers, but if you are generating human data ... I'll fix it.

**Comment by jory** [comment]
Should just require the addition of a `+ 1` over here https://github.com/Marak/faker.js/blob/master/examples/browser/index.html#L122

**Comment by natzar** [comment]
Done. Tried to mantain simplicity. Comment added.
