### ISSUE TITLE
Gender of images and names do not match

### ISSUE THREAD

**Issue by zachpanz88** [Marak/faker.js#331]
I don't know much node and therefore I am submitting an issue rather than a PR.

Often times a name will be generated that does not match the gender of the person in the profile picture. 

Possibly a patch could be created where names and images are tagged with a gender, and therefore the gender of the name will match the gender of the person in the image. This would help give a more realistic feel to the information generated. Also, take note that some names are unisex.

**Comment by Marak** [comment]
@zachpanz88 

The source of images we use doesn't provide this.

What would be nice, is if we started a new folder in the project for local assets. If you pulled all the open-source images available from amazon and put them into a directory, we could then tag them in our locale data by gender.

If you can get the images checked into the repo we can start to figure out how to tag them.

Moving forward, I can provide a stable public API endpoint for serving the data ( so users don't have to ship their libraries with images )
