### ISSUE TITLE
Using regexes to generate some of the random data

### ISSUE THREAD

**Issue by jdrew1303** [Marak/faker.js#332]
Hi all, 

Ive been working on merging some of the ideas for credit card generation that are in the pull requests and cleaning them up. During testing I was using regex (along with the luhn check) to make sure the cards had the right format. It got me thinking if it would be possible to generate a string from a regex. [It turns out that there is a library that can do this.](https://github.com/fent/randexp.js)

I always try to keep dependencies out of lower level libraries but I think that this could be a great option to add in to help generate some types of random data (credit cards, phone numbers, emails, etc). In some cases it could completely remove a lot of the code necessary for random generation (including in my own contributions for random.uuid).

I can do the work on this if people are interested?

**Comment by Marak** [comment]
@jdrew1303 -

I'd be interested in seeing a reduction of complexity if we could include `regexp` project. I've actually looked into incorporating this project into `faker` before.

I would recommend you first review the existing methods we have to helping generate fake data.

https://github.com/Marak/faker.js/blob/master/lib/helpers.js
https://github.com/Marak/faker.js/blob/master/lib/fake.js

I would then start by finding the best area in `faker` for improvement and open a small pull request ( with not too many changes ) using `regexp`. We can review the implementation from there and if it looks good move forward with updating the entire `faker` project.

**Comment by jdrew1303** [comment]
@Marak 

Sure no problem. Ill try to pick something meaty that can show the reduction. It might also allow us to generate the unit tests automatically for a lot of the functionality. 

Can I ask what stopped you using it before? (Just to see if its still an issue or not.)

**Comment by Marak** [comment]
Nothing stopped me. I was able to move forward with the functionality I required at the time using some of the now existing `faker` methods.

**Comment by jdrew1303** [comment]
Ah ok. Thats fair enough.

I've submitted a few examples in the pull request. I think that using metaprogramming and the localised data files we could use this to handle most of the randomisation. The good thing about it is that it could be quite quickly ported to other languages just by porting the engine.

**Comment by jdrew1303** [comment]
Based on pull #333 then this should also be closed.
