### ISSUE TITLE
SK locale not working

### ISSUE THREAD

**Issue by achtan** [Marak/faker.js#336]
Hi, `sk` locale not working, i'm getting `en` locale results, my code:
`````
import faker from 'faker/locale/sk';

faker.locale = "sk"; // make sure

console.log(faker.name.firstName())
````
(i tested `ru` locale and that's working fine!)

**Comment by Marak** [comment]
Good catch @achtan !

I've pushed a fix and this should be resolved in `master`. This will be included in the next release.

Thank you for your contribution.
