### ISSUE TITLE
Improved city name generation

### ISSUE THREAD

**Issue by Niels-NTG** [Marak/faker.js#337]
I can't help but notice that the cities Faker generates are almost always constructed of a first name or last name with a typical place name suffix or prefix. I guess this might make sense in most English speaking parts of the world. But very rare in places like The Netherlands, Germany and other nations in continental Europe.

This could be improved by pulling random names from real places from the [GeoNames](http://www.geonames.org/) database. I suppose relying on another service would make Faker less reliable. Alternatively you could have a pre-defined smaller list of names for each language, similar in how the game OpenTTD does its [town names](https://dev.openttdcoop.org/projects/dutchtowns/repository/revisions/2f116ac13084/entry/dtnames.nml) for each language.

**Comment by Marak** [comment]
@Niels-NTG -

I feel like some of the locales actually have city data, maybe not.

If you are able to make a pull request adding arrays of common cities to any of the locales, it would be very much appreciated.

Thank you for your feedback.

**Comment by Niels-NTG** [comment]
I've noticed that faker.js completely ignores the city format defined in `lib/locales/[some locale]/address/city.js` and instead uses a random one defined in this array in [`lib/address.js`](https://github.com/Marak/faker.js/blob/master/lib/address.js):
```
this.city = function (format) {
    var formats = [
      '{{address.cityPrefix}} {{name.firstName}} {{address.citySuffix}}',
      '{{address.cityPrefix}} {{name.firstName}}',
      '{{name.firstName}} {{address.citySuffix}}',
      '{{name.lastName}} {{address.citySuffix}}'
    ];

    if (typeof format !== "number") {
      format = faker.random.number(formats.length - 1);
    }

    return f(formats[format]);
}
```

This is a shame because their already some locales that have different formats defined in their `city.js` files. The France locale for example has [city names defined as `city_name`](https://github.com/Marak/faker.js/blob/master/lib/locales/fr/address/city.js) from the [`city_name.js`](https://github.com/Marak/faker.js/blob/master/lib/locales/fr/address/city_name.js). Due to the current method these entries never get used anywhere.

The format for city names should be pulled from `lib/locales/[some locale]/address/city.js` instead of a predefined array in `lib/address.js`. I've made some attempts making this happen, but haven't been successful thus far. Perhaps somebody with a better understanding of the project structure can do this instead. I will stick with Dutch town names for now.

**Comment by Marak** [comment]
Good catch!

I'll see if I can sort it out.

**Comment by Marak** [comment]
This should be resolved in `master`.

Please let us know! You might need to add the cities for your specific locality.

Thanks!
