### ISSUE TITLE
Using date.between

### ISSUE THREAD

**Issue by hamzaOp** [Marak/faker.js#344]
I want to generate some dates between two fixed values , but in the [demo](http://marak.com/faker.js/#date)  `faker.date.between` just returns `null` with no example how to use it.

**Comment by Marak** [comment]
Try reading the API documentation or reading the unit tests.

The demo currently provides a very basic and generic auto-generated interface for accessing the core API.

**Comment by hamzaOp** [comment]
Thank you , it worked 

    self.between = function (from, to) {
      var fromMilli = Date.parse(from);
      var dateOffset = faker.random.number(Date.parse(to) - fromMilli);

      var newDate = new Date(fromMilli + dateOffset);

      return newDate;
     };
