### ISSUE TITLE
Creating own (depended) data-sets (like software-product-name, software-product-description)

### ISSUE THREAD

**Issue by webia1** [Marak/faker.js#367]
Hello dear faker team, 

how can I create own data-sets (maybe a link to a tutorial for me) ?

Second question: The description should come from corresponding software-product-name, how could I achieve that? (depended data sets -> software and its description)

thank you!

**Comment by Marak** [comment]
just look at how the other data sets are included in the library and follow the same pattern

you are welcome!

**Comment by webia1** [comment]
Thank you, creating of data sets is not the problem, my question is, how can I generate random entries from depended data structures:

    software: {
        1: {
            name: "X",
            description: " Description of X"
        },
        2: {
            name: "Y",
            description: " Description of Y"
        },
       ....
       ....
    }

If I generate random values with lodash e.g.


    return {
        "software" : _.times(20, function (n) {
            return {
                "id": n,
                "name": faker.software.name(),
                "description": faker.software.description()
            }
        })
    }

should the software.description match to given software.name. Did you consider such of use cases maybe?
