### ISSUE TITLE
http://marak.com/faker.js/ is down with a 404

### ISSUE THREAD

**Issue by pogopaule** [Marak/faker.js#384]

**Comment by 0wczar** [comment]
When it come back?

**Comment by nightire** [comment]
FYI: http://marak.github.io/faker.js

**Comment by 0wczar** [comment]
But it is not are real examples!

**Comment by vishivish18** [comment]
@Marak Any update ?

**Comment by nightire** [comment]
The real working example is already included in this repo: https://github.com/Marak/faker.js/tree/master/examples/browser

Just clone it & open it in your browser, how hard could it be?

**Comment by vishivish18** [comment]
@nightire Thanks

**Comment by 0wczar** [comment]
@nightire thanks.

**Comment by jocull** [comment]
I miss the old page because I would frequently pop open a console and play with faker right there on the site for new samples. It was more convenient than having to clone something or fire up a REPL.

**Comment by lolmaus** [comment]
Same.

**Comment by Marak** [comment]
I will try to fix now, sorry for the downtime. I think Github updated some of the non-public APIs I was using.

**Comment by 0wczar** [comment]
& pls fix working `https://github.com/Marak/faker.js/tree/master/examples/browser` on safari (OSX).

**Comment by ericclemmons** [comment]
This works:
> https://cdn.rawgit.com/Marak/faker.js/master/examples/browser/index.html
