### ISSUE TITLE
random.number precision option needs improvement

### ISSUE THREAD

**Issue by WattsC-90** [Marak/faker.js#401]
using this code:

`var faker = require("Faker")
var options = {min: 0, max: 10, precision:1}
options.precision
faker.random.number(options)`

i would expect a number between 0 and 10 to be returned, but i just get NaN. looking at the code this is what i would expect to happen.
I am simply trying to understand the methods in order to generate a float, there doesnt appear to be much documentation around these methods.

Does anyone have any idea what i am doing wrong?

**Comment by paolodm** [comment]
![screen shot 2016-09-24 at 11 06 47 pm](https://cloud.githubusercontent.com/assets/247525/18812740/9b0b7762-82ab-11e6-99ce-c9963c80d235.png)

Seems to be working for me, @WattsC-90.

**Comment by kristianmandrup** [comment]
I don't understand how to use the `precision` option for `random.number` please document it in readme or in the header comment for the function. All the examples (and default value) use `1`

How do I return a float with a given precision, such as `4.23` ???

**Comment by kelsonic** [comment]
I get this same issue... interested if anyone else is having this problem.

**Comment by Marak** [comment]
I'll see what happened with `random.number` and precision.

It could be a possible regression. If anyone has a failing unit test please let me know, it would really help.

**Comment by kristianmandrup** [comment]
I made a lot of fixes and improvements in a new fork published as a separate npm module

**Comment by Marak** [comment]
If anyone has a failing unit test please let me know, it would really help.

**Comment by Marak** [comment]
@WattsC-90 - Based on your code it looks like you are requiring `Faker` package. That is not the correct package name, package name is `faker`.

**Comment by Marak** [comment]
@kelsonic - Make sure to require `faker` package, and not `Faker` package.

**Comment by Marak** [comment]
I'm seeing that `faker.random.number` is currently working like:

```
var options = {min: 0, max: 10, precision:0.0001};
console.log(faker.random.number(options));
// outputs: 2.4658
```

I'm not sure that is the best way the API should be exposed, but it does appear to be mostly working.

**Comment by kelsonic** [comment]
@Marak Perfect, that was it. Thanks! :)

**Comment by WattsC-90** [comment]
@Marak Thanks for that, that seems to have been the problem! however, quick test using the following script and Json-server seems to ignore the precision argument.. see below: 

```javascript
module.exports = function(){
	var maxNumberCount = 100;
	var faker = require("faker");
	var _ = require("lodash");
	var tmp = _.times(maxNumberCount, function(n){
		return {
			number:faker.random.number({min: 0, max: 10, precision:0.0001})
		};
	});
	return {
		numbers: tmp
	};
}
```

results in:
```javascript
[
  {
    "number": 4.0579
  },
  {
    "number": 6.203600000000001
  },
  {
    "number": 1.8840000000000001
  },
  {
    "number": 3.3238000000000003
  },
  {
    "number": 3.6625
  },
  {
    "number": 1.1754
  },
  {
    "number": 6.9989
  },
  {
    "number": 9.6952
  },
  {
    "number": 9.1448
  },
  {
    "number": 3.8464
  },....
]
```

which as you can see, ignores (sometimes) the 0.0001 precision. Thanks for your help though!! much appreciated, I was doing a string concatenation of two faker.random.numbers between 0 and 10000..... =D

**Comment by Marak** [comment]
@WattsC-90 - Good catch.

I also noticed the precision issue happening locally in testing a few days ago.

I believe this is a rounding / floor issue. JavaScript `Number` type is going a little crazy and we didn't round off the unexpected extra decimals.

I'll add a patch to this for the upcoming release. Thank you.

**Comment by geekinate1** [comment]
I'm getting the value of `NaN` rather than a number for `amount`:

```
total: faker.finance.amount({ min: 1000, max: 100000 }),
```
