### ISSUE TITLE
Demo link does not work, displays a 404 message

### ISSUE THREAD

**Issue by eddiejaoude** [Marak/faker.js#406]
<img width="1680" alt="screenshot 2016-08-31 17 06 50" src="https://cloud.githubusercontent.com/assets/624760/18136699/8c54750a-6f9d-11e6-861a-896e33c25e26.png">

**Comment by zbarbuto** [comment]
Duplicate #384

**Comment by eddiejaoude** [comment]
Thanks @zbarbuto 👍
