### ISSUE TITLE
Custom helpers

### ISSUE THREAD

**Issue by gotofritz** [Marak/faker.js#409]
Hi. Is there a preferred way to define custom helpers, other than just adding a dynamic method to the faker instance?

**Comment by Marak** [comment]
There is the documented `faker.fake` method, outside of that developers are responsible for making their own modules for defining custom helpers / extending faker.

**Comment by developer239** [comment]
I guess the correct answer is no. We have to create our own modules. `faker.fake` interpolates existing methods. It is not possible to create new custom methods atm.
