### ISSUE TITLE
SHASUM failure from npm

### ISSUE THREAD

**Issue by nordsimon** [Marak/faker.js#410]
Hello

The npm install fails due to SHA sum calculation

```
npm ERR! Expected: 0f908faf4e6ec02524e54a57e432c5c013e08c9f
npm ERR! Actual:   88750f99f2d611a664d4b350a6b431edbbafcb94
npm ERR! From:     https://registry.npmjs.org/faker/-/faker-3.1.0.tgz
```

Faker 3.0.0 works alright

**Comment by Marak** [comment]
Try running `npm clean cache` and re-installing?

I believe this is a local npm issue. You may need to update npm.

**Comment by gongzza** [comment]
still getting same error..

``` bash
```

**Comment by Marak** [comment]
Try

`npm cache clean`

Or updating NPM itself

**Comment by Marak** [comment]
This is most likely an NPM or local env issue.

`npm cache clean` or updating Node and NPM should resolve it.
