### ISSUE TITLE
Support Faker Development on Patreon 

### ISSUE THREAD

**Issue by Marak** [Marak/faker.js#413]
I'm looking to put more time into faker.js development and have launched a Patreon campaign to help fund the effort.

[https://www.patreon.com/marak](https://www.patreon.com/marak)

For as little at $10.00 a month, you could help ensure the future of this project. There are rewards for all levels of pledges including getting your logo in the README file ( which currently gets 30k uniques a month ). If we can reach the initial goal I'll be able to triage all the current issues and get a new release out soon.

If you run a business and are using faker.js in a revenue-generating product, it would make business sense to sponsor faker development: it ensures the project that your product relies on stays healthy and actively maintained.

Of course, individual users are also welcome to make a recurring pledge if faker.js has helped you in your work or personal projects :)

**Comment by VladimirPal** [comment]
@Marak The link is broken

**Comment by pushred** [comment]
If Patreon's not quite working out https://opencollective.com is picking up some traction. I'd totally throw $5/mo your way anywhere you can get something up and running. Very helpful project!

**Comment by Marak** [comment]
Not sure what happened with Patreon???

I got no emails or notice from them saying it went offline.

Will follow-up tonight.

**Comment by Marak** [comment]
Just tweeted at Patreon. https://twitter.com/marak/status/829796317140508677

Maybe they flagged the Faker account as Spam? I have no idea. I got no messages from them at all.

Going to re-evaluate and see if https://opencollective.com/ is a better solution.

**Comment by Marak** [comment]
Going to try https://opencollective.com/fakerjs and see how it works...
