### ISSUE TITLE
npm install is failing with 404

### ISSUE THREAD

**Issue by jmona789** [Marak/faker.js#416]
I'm trying to npm install faker.js and I'm getting the following error:

npm ERR! fetch failed https://registry.npmjs.org/faker.js/-/faker.js-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/faker.js/-/faker.js-2.0.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/faker.js/-/faker.js-2.0.0.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/Users/JamesMona/.node/bin/npm" "install" "faker.js" "--save"
npm ERR! node v4.2.1
npm ERR! npm  v3.5.3

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/JamesMona/Development/brainiac/gg-concierge/npm-debug.log

**Comment by Marak** [comment]
Latest published version is `3.1.0`, not `2.0.0`. Package name is `faker` not `faker.js`

Try running:

`npm install faker`

**Comment by jmona789** [comment]
Thank you, that worked
