### ISSUE TITLE
feature : provide dataURL or images for offline use

### ISSUE THREAD

**Issue by sylvainbannier** [Marak/faker.js#420]
When working offline images URL like the ones provided by `image.avatar` are not available.

Is it possible to provide dataURL or images from the faker package instead ?
maybe like that : 
`image.placeholder(width, height)`

**Comment by Marak** [comment]
Sounds good.

Will accept pull request.

**Comment by sylvainbannier** [comment]
OK I'll try. which solution do you prefer ? dataurl or static asset in the lib ?
IMO dataurl seems a better choice as it doesn't require to work with filepath to access asset from HTTP

**Comment by sylvainbannier** [comment]
I made a pull with a minimal implementation providing basic grey rectangle with dimensions.
Is it usable enough ?

`image.dataurl(200,300)` : 

![image](https://cloud.githubusercontent.com/assets/452941/19107387/42cb8ae4-8aec-11e6-9fe1-816f4ae08545.png)

do you need some extra features or styles updates ?

**Comment by pgAdmin** [comment]
@sylvainbannier I think you can add a 3rd optional parameter -  color, which accepts hexcode. Absence or this defaults to grey like it is right now.

Eg: image.dataurl(200, 300, '#005500')

**Comment by Marak** [comment]
@sylvainbannier - Seems good. Will review and merge PR for next release.

@pgAdmin - Did you have any additions to this you wanted to see? Any code would help.

**Comment by Marak** [comment]
Merged into `master`.

Thank you for your contributions.

Please let me know if you want to improve on this at all for the next release.
