### ISSUE TITLE
Publish latest version on npm?

### ISSUE THREAD

**Issue by NickHeiner** [Marak/faker.js#433]
I would like to use the `internet.ipv6` method, which was added in fc9d5351cd34d741538a364a31d22ae0c0f8101e, from October 1. However, the current version of `faker` on npm is `3.1.0`, which was published `2016-03-21T01:21:12.255Z`. 

Can you publish the latest version? Thanks!

**Comment by randy5235** [comment]
+1

**Comment by denzo** [comment]
Yes please! Missing a really useful
"`alphaNumeric` now takes count as a argument"
https://github.com/Marak/faker.js/commit/3de06918d890e48e7964de71ca0c95717d6213e5

**Comment by rochdev** [comment]
+1 I also need the `count` argument for `alphaNumeric`

**Comment by Marak** [comment]
Will try to publish this weekend.

**Comment by Marak** [comment]
Publish coming soon. Triaging issues now.

**Comment by Marak** [comment]
`v3.2.0` is now pending release

https://github.com/Marak/faker.js/issues/463

**Comment by NickHeiner** [comment]
Thanks!

**Comment by Marak** [comment]
Latest version `4.0.0` has been released.

Decided to not do another v3 release.

Cheers!
