### ISSUE TITLE
Generate different sets of data

### ISSUE THREAD

**Issue by aabanaag** [Marak/faker.js#438]
I have a model, `Player` and I'm assigning faker data to default values (btw, I'm using jagi:astronomy and meteor).

```
brand: {
      type: String,
      default: faker.commerce.product()
    },
    balance: {
      type: Number,
      default: faker.finance.amount()
    },
    affiliate: {
      type: String,
      default: faker.company.companyName()
    },
```

then I'm creating new model via 

```
_.each(res.data, (data) => {
   let player = new Player
  player.set(data);
});
```

But what I got is the same set of faker data for all. Is there a way to generate different sets of faker data?

**Comment by Marak** [comment]
@aabanaag 

Faker should be generating unique data by default ( with a fresh random seed ).

If you aren't seeing that, it's most likely an issue with how you are using Faker itself. I wish I could assist more, but without a reproducible code snippet, there is little I can do here.

I'd recommend trying to clone Faker from Github and running the examples locally to get started.
