### ISSUE TITLE
Can't install via NPM

### ISSUE THREAD

**Issue by jdgriffith** [Marak/faker.js#443]
When I try to install faker.js via NPM, I receive a fetch error. Evidently NPM is reporting the compressed library lives here: https://registry.npmjs.org/faker.js/-/faker.js-2.0.0.tgz

But you get a 404 when you go directly to this link. You can also see where NPM's API show this as the proper download location but something is wrong: https://registry.npmjs.org/faker.js. 

Can you do anything to correct this? Maybe even `npm publish` again?

**Comment by Marak** [comment]
Package name is `faker` not `faker.js`

Try: `npm install faker`

**Comment by jdgriffith** [comment]
Ok thanks. Why is it still listed as faker.js even with NPM? Is this a recent change?

**Comment by Marak** [comment]
Listed where @jdgriffith?

**Comment by jdgriffith** [comment]
https://www.npmjs.com/package/faker.js

And proper pointers for what to install and how to install would be nice here: https://github.com/FotoVerite/Faker.js There isn't a section under node.js which basically says `npm install faker` unless I am missing it.
