### ISSUE TITLE
npm needs to be updated to the latest version of this repo

### ISSUE THREAD

**Issue by maludwig** [Marak/faker.js#444]
Hey, I was having some trouble getting Faker to work properly in Nodejs, specifically, I had trouble getting Dates to work properly. The "past" function was 24x smaller than it should have been. Suspecting that a multiplication was wrong, I check this git repo out, and it seemed to include the 24. I looked locally, and sure enough the 24x multiplier was missing. Please update the npm package.

**Comment by Marak** [comment]
Will be releasing a new version soon.
