### ISSUE TITLE
[feature request] allow user to exclude certain words from .words()

### ISSUE THREAD

**Issue by martahj** [Marak/faker.js#449]
I use `.words()` to simulate test data, and sometimes it comes back with words that cause a validation function to fail. It would be helpful if the user could optionally pass in an array of words to exclude from the output, so that any time those words came up they would be 'rerolled'. 

Happy to put in a PR on this too :)

Thanks!

**Comment by Marak** [comment]
@martahj 

I'm not sure exactly how this would actually work.

If you think this functionality would be useful for others, a PR would be much appreciated.

Cheers.

**Comment by Marak** [comment]
@martahj -

Which words specifically are causing you issues?

**Comment by thomasspiesser** [comment]
It would be great if one could provide a list with e.g. blacklisted names to `faker.name.firstName({ blacklist: ['Adolf'] })`

**Comment by Marak** [comment]
We now have the ability to exclude results for any faker API using new `faker.unique` method [available in master](https://github.com/Marak/faker.js/blob/master/vendor/unique.js).

```js
var excludeArr = ['nesciunt', 'qui', 'dolor'];
var result = faker.unique(faker.lorem.words, [2], { exclude: excludeArr });
```

`faker.unique` takes three arguments. `method`, `arguments`, `options`. 

In `options` we can specify an array of `exclude` values to be excluded  from results. Implementation has time / loop count / predictable state.

Closing issue for now. Let me know if it doesn't work or you have any suggestions and I'd be glad to review.
