### ISSUE TITLE
Is it possible to turn off the randomness?

### ISSUE THREAD

**Issue by jantimon** [Marak/faker.js#456]
Hi,

for snapshot testing it would be nice to turn off the randomness is that possible?

Thanks :)

**Comment by jantimon** [comment]
@Marak is this possible?

**Comment by pgn-vole** [comment]
I'm interested by this question as well.

**Comment by jantimon** [comment]
The code supports it - it's just not exposed as an option:

https://github.com/Marak/faker.js/blob/7e96b93869b422af5a63c115e04ff0206bf7b228/lib/index.js#L45

It would have to be changed to:

```js
var Random = require('./random');
self.random = new Random(self, opts.seed);
```

**Comment by Marak** [comment]
Making the random seed configurable seems OK.

I'll do a bit of testing and see if I can easily add this.

**Comment by Marak** [comment]
@jantimon -

I've exposed `seed` as an option to the `Faker` class.

This should address your requirements? Let me know.

Will be included in the next release.

**Comment by pgn-vole** [comment]
Thanks @Marak for the quick fix!

**Comment by jantimon** [comment]
perfect :)
