### ISSUE TITLE
Passwords don't use `faker.seed`

### ISSUE THREAD

**Issue by cazgp** [Marak/faker.js#460]
Generating a bunch of random data using `faker.seed` to ensure test reproducibility. Everything works apart from passwords, and that's because the password module uses `Math.random` which cannot be seeded. Could the password instead use `faker.random.number`?

**Comment by Marak** [comment]
Seems reasonable. 

The use of `Math.random` is probably a bug now since we've previously migrated to the user `faker.seed` everywhere else.

Will fix.

**Comment by Marak** [comment]
Should be resolved in `master`.
