### ISSUE TITLE
Readme: Node examples not working. Examples are lower case, but must be capitalized.

### ISSUE THREAD

**Issue by mauricedoepke** [Marak/faker.js#474]
Node Version: 6.9.5
Faker Version: 0.7.2

The  Readme shows this examples for the use in Node.js
```
var faker = require('faker');

var randomName = faker.name.findName(); // Rowan Nikolaus
var randomEmail = faker.internet.email(); // Kassandra.Haley@erich.biz
var randomCard = faker.helpers.createCard(); // random contact card containing many properties
```
`require('faker');` however returns an Object where the childobjects like name or internet are capitalized.

So one must for example use

`var randomName = faker.Name.findName();` to retrieve a name from Faker

**Comment by Marak** [comment]
The project name is `faker`, not `Faker`.

You are using the wrong version.
