### ISSUE TITLE
Hacker phrase templates localization

### ISSUE THREAD

**Issue by dhilt** [Marak/faker.js#483]
Good day!

As it was disscussed in https://github.com/Marak/faker.js/issues/475 issue, the phrase templates locale customization is needed (Hacker generator). A translator should be able to make its own phrase templates to satisfy his language specifics.

I made a PR on this topic: https://github.com/Marak/faker.js/pull/482. Hope it is clear and acceptable!

**Comment by dhilt** [comment]
@Marak If you want to adjust the logic before master-merge and don't want lose my PR, you may create a separate branch, and then I will reopen my PR to that branch... Thanks!

**Comment by Marak** [comment]
#482 merged
