### ISSUE TITLE
shortest & longest texts

### ISSUE THREAD

**Issue by tomByrer** [Marak/faker.js#484]
Is there a way to adjust the character lengths of output?

I've found layout issues in testing for texts that are too long (usually long last names).  Sometimes too short texts might cause issues (eg if a [2 character last name](http://projects.newsday.com/databases/long-island/census-last-names/?where=name*li&offset=0) causes too small of a click box).

Related; Is there a way to create [hyphenated names](http://www.npr.org/2012/07/19/156923573/when-hyphen-boy-meets-hyphen-girl-names-pile-up)?

Thanks for your great tool!

**Comment by Marak** [comment]
Not really possible right now. You could always just create a helper method which truncated the result to whatever length you wanted.

I'd suggest building layouts which can accommodate names of any length.

If you want to create custom formatted names, you can try using the `faker.fake` method.
