### ISSUE TITLE
Generate Mobile Phone Number

### ISSUE THREAD

**Issue by minhchu** [Marak/faker.js#501]
Do we have any way to generate only mobile phone number or
may we have to implement something like `faker.phone.mobilePhoneNumber()`

**Comment by genu** [comment]
whats the difference between a mobile phone number and a regular phone number?

**Comment by Marak** [comment]
@minhchu -

What is the difference between a mobile phone number and a regular phone number?

**Comment by minhchu** [comment]
In my country, there is difference. For example:
Home phone number: **043**8128364
Mobile phone number: **0165**7829433

And I found another way to do it 
```
faker.phone.phoneNumber('0165#######')
```
