### ISSUE TITLE
Request / Clarification needed: AMD Compatibility (Aurelia CLI / JSPM)

### ISSUE THREAD

**Issue by cornillemichiel** [Marak/faker.js#504]
The documentation seems to imply that either you use fakerjs in the browser, or with nodejs. 

**But I want to do a bit of both**. I want to require the faker module in the browser, which is (correct me if wrong) not possible because it doesn't seem like there is AMD / CommonJS support?. In future versions of our application we'd even like to use JSPM to install faker. 

Some context. We are using Aurelia framework and I was unable to set up Aurelia with faker.js because .. well .. the faker.js file is not even in the node_module! Modding it to load the index.js file requires /lib but that is not supported in the browser!

Thanks in advance!

**Comment by boblgum** [comment]
same here 👍

**Comment by Marak** [comment]
I don't really understand the problem.

`faker.js` was built around CommonJS format for server-side require and currently uses [browserify](https://github.com/browserify/browserify) for generating browser builds using [stand-alone option](https://github.com/Marak/faker.js/blob/master/build/gulpfile.js#L44) to create `faker` namespace.

If you need to support additional browser module formats, it should be easy to take the server-side CommonJS module and convert it to whatever format you need.

Closing unless you can provide additional information of exactly what isn't working.
