### ISSUE TITLE
lorem.word(num) always return random length word

### ISSUE THREAD

**Issue by adoyle-h** [Marak/faker.js#509]
![image](https://cloud.githubusercontent.com/assets/1998490/26149363/934d95ac-3b2c-11e7-8cfa-4bb60f8855a8.png)
The length of word should equal the input number, but actually Not.

**Comment by jreina** [comment]
This appears to be related to #500 
@Marak can you clarify the usage of this method? I could not find a unit test. I don't mind digging into this but I would like to make sure that I'm not breaking the intended use.

**Comment by Marak** [comment]
It looks like `num` argument may be ignored.

see: https://github.com/Marak/faker.js/blob/master/lib/lorem.js#L16

This appears to be an error. A unit test / patch would be appreciated. Thank you.

**Comment by rmoskal** [comment]
So what's up with this?  Almost seems like a deal breaker.  I always wonder if people actually use these libraries with a half million downloads a week.

**Comment by lucasmarques73** [comment]
Hey, you can use `faker.random.alphaNumeric(num)`   
This way works for me!
