### ISSUE TITLE
internet.userAgent() doesn't respect seed

### ISSUE THREAD

**Issue by djones** [Marak/faker.js#521]
This is probably the bit that needs updating: https://github.com/Marak/faker.js/blob/master/vendor/user-agent.js#L83-L89

**Comment by Marak** [comment]
Interesting.

Could you make a patch to fix this?

Would be glad to merge it in.

**Comment by Marak** [comment]
This seems like it should be a relatively easy fix.

Can anyone do the refactor for this section to use the random seed like the rest of faker?

**Comment by Marak** [comment]
Should now be resolved in `master`

Good catch!

Thanks again @djones
