### ISSUE TITLE
Generating a word from a pre-defined words list?

### ISSUE THREAD

**Issue by gkatsanos** [Marak/faker.js#531]
Is it possible to generate a word / string from a pre-defined list of strings we can provide?

**Comment by Marak** [comment]
Yes.

**Comment by gkatsanos** [comment]
Thank you for the fast and detailed answer.
For the people who will see this in the future, the way to do this is to use the random.array_element() method:
`faker.random.array_element(['train', 'bicycle', 'street'])`
