### ISSUE TITLE
Web Portal Not Generating Results : Console Throws Exception

### ISSUE THREAD

**Issue by justinkneff** [Marak/faker.js#547]
When trying to generate a new fake identity the page throws an exception and only fills in the Name.

index.html:124 Uncaught TypeError: faker.name.gender is not a function
    at generateName (index.html:124)
    at HTMLButtonElement.<anonymous> (index.html:138)
    at HTMLButtonElement.handle (jquery.js:55)
    at HTMLButtonElement.o (jquery.js:49)

Same results for Chrome 60.0.3112.113 and Edge

**Comment by Marak** [comment]
Good catch.

I think someone accidentally ran the gulp publish script for docs on the new version before it was ready for release.

Let me see what I can do to fix this now.

**Comment by Marak** [comment]
For some reason rawgit.com won't uncache the old version.

You can try: https://rawgit.com/Marak/faker.js/master/examples/browser/index.html for now

I'll be removing rawgit.com completely. It's an unreliable host for demo pages.
