### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by Dylan-DPC** [Marak/faker.js#561]
Hey

It would be nice if you convert the `docs` folder from html files to a readme file with that content.

**Comment by Marak** [comment]
Sounds good.

Will accept PR.

**Comment by Dylan-DPC** [comment]
I will try to do it if i have time. I say it is better to open this issue for "hacktoberfest"

**Comment by Marak** [comment]
Sounds good. Define the scope of the work and post it.

**Comment by Dylan-DPC** [comment]
Scope: Create readme files instead of html files in docs folder with the same content.

**Comment by Marak** [comment]
Scope isn't clear enough. Closing.

**Comment by Marak** [comment]
Also I just found: https://github.com/jsdoc2md/jsdoc-to-markdown, which may help.

**Comment by Marak** [comment]
Let's see if anyone can create a simple and eloquent solution here. There is already good tooling in place for documentation generation. Just need to add that to the gulp build pipeline.

Scope still seems really unclear. Write up a better description or get hacking. Cheers.
