### ISSUE TITLE
Browser support through npm

### ISSUE THREAD

**Issue by caseywatts** [Marak/faker.js#575]
It looks like we got rid of the `builds/builds/faker.js` file in the published npm package, [here](https://github.com/Marak/faker.js/pull/432).

I'm working in a project that was depending on that one file. We usually wrap the browser-exported version (like `faker.js`). I'm not sure how else we can update to 4.0 without this built file being present:
https://github.com/samselikoff/ember-cli-mirage/issues/1037
https://github.com/samselikoff/ember-cli-mirage/pull/1062

Could we include just `builds/builds/faker.js` into the build? If we used the `package.json` feature `files`? (like mentioned [here](https://github.com/Marak/faker.js/pull/432#issuecomment-259269892))

At a glance, I think we would whitelist these folders/files:
```
lib
locale
vendor
index.js
builds/builds/faker.js
builds/builds/faker.min.js
MIT-LICENSE.txt
```

and maybe also
```
bower.json
package.json
package.js
```

Does that seem right?

Here's the full list of what's currently published to NPM:
![image](https://user-images.githubusercontent.com/273653/32568772-3ef311fe-c48d-11e7-8b46-9abfa81728f6.png)

**Comment by caseywatts** [comment]
cc @schovi @knownasilya @Marak :)

btw - one reason I want to update to 4.0 is because the npm package filesize is so dramatically smaller! I'm totally onboard with the PR that did that ✨

**Comment by Marak** [comment]
I think I see what happened.

@caseywatts - I'll see if we can re-include the main faker.js browser build file.

**Comment by caseywatts** [comment]
I took a stab at it! :)

https://github.com/Marak/faker.js/pull/584
