### ISSUE TITLE
faker.random.words() returns phrases, not words

### ISSUE THREAD

**Issue by ffxsam** [Marak/faker.js#602]
```
> faker.random.words(4)
'Home Loan Account quantifying Auto Loan Account Credit Card Account'
```

Technically it's returning phrases, not words. It would be nice if `.words()` actually did return words, and maybe we had another function `.phrase()` and `.phrases()`?

**Comment by travis-flint** [comment]
What is happening is that it calls the word() function and some of the library sets have more than one word for each value (maybe more, or maybe some don't apply):
commerce.productName
address.state
finance.accountName
finance.transactionType
name.jobDescriptor
name.jobArea
name.jobType

**Comment by aboveyou00** [comment]
As @travis-flint said, this is a side effect of #661 . I just wanted to reference the issue to make it clear that this is already being tracked elsewhere.
