### ISSUE TITLE
Regex pattern generating invalid data

### ISSUE THREAD

**Issue by Gabology** [Marak/faker.js#623]
For the following schema:

```json
{
  "type": "object",
  "properties": {
    "countryCode": {
      "type": "string",
      "minLength": 1,
      "maxLength": 3,
      "pattern": "^[0-9]{1,3}?$"
    },
    "nationalNumber": {
      "type": "string",
      "minLength": 1,
      "maxLength": 14,
      "pattern": "^[0-9]{1,14}?$"
    }
  }
}
```

This data was generated:

```json
[
  {
    "countryCode": " ",
    "nationalNumber": "255359182"
  },
  {
    "countryCode": "11",
    "nationalNumber": " "
  }
]
```

In both cases the generated string will not match the regexp `^[0-9]{1,3}?$` and `^[0-9]{1,14}?$` respectively. This was tested on version 0.5.0-rc15 and can easily be reproduced.

**Comment by Marak** [comment]
Ugh, we don't have support for schemas?

**Comment by Marak** [comment]
and the latest version of Faker is `v4.1.0`.

I have no clue what a `0.5.0-rc15` is.

**Comment by Gabology** [comment]
Crap! Sorry I submitted this to the wrong repository .
