### ISSUE TITLE
NPM PACKAGE: Please publish a new release to npm.

### ISSUE THREAD

**Issue by armand1m** [Marak/faker.js#628]
# Problem

[This PR](https://github.com/Marak/faker.js/pull/382) was merged last year adding functionality to generate creditCardNumber based on the issuer.

[This issue](https://github.com/Marak/faker.js/issues/626) is open to add this new methods to the README.md of this repository. Even has a [PR](https://github.com/Marak/faker.js/pull/627) regarding this.

But, when trying to use this code with the actual deployed release in `npm`, this is what we get:

`TypeError: faker.finance.creditCardNumber is not a function`

And when looking up the code in `node_modules`, we cannot find this method there.

**Current version being used:**
`"faker": "^4.1.0"`

## Reason

#382  was merged in Sept 2017.  
The last release published to npm was in **Feb 2017**. 

## Acceptance Criteria

- [ ] A deployment of a new release _(4.2.0)_ containing new code. 

##  Disclaimer

Would be awesome to see this project using `semantic-release`.  Would at least get out the burden of being constantly creating and publishing releases to npm, and let the CI system do it.

**Comment by Marak** [comment]
Duplicate #621 #583

**Comment by armand1m** [comment]
@Marak if this is of your interest, I can take care of the maintenance of this application.

**Comment by Marak** [comment]
Sure go for it.

**Comment by armand1m** [comment]
Ok, so how should we start it?

**Comment by armand1m** [comment]
Ok, sorry for the delay, for a first step I guess this would be a good idea:

 - Configure semantic version in my fork
 - Rename it so I can publish it to registry _(suggestions are welcome)_
 - Move some of the issues from this repo to the next one _(maybe using this https://github.com/E3V3A/gh-missue since it can copy issues from a repo to another)_

Please let me know your thoughts
