### ISSUE TITLE
system.filePath & system.directoryPath always undefined

### ISSUE THREAD

**Issue by nuthinking** [Marak/faker.js#633]
I can see this also on the [demo page](https://rawgit.com/Marak/faker.js/master/examples/browser/index.html).

**Comment by Marak** [comment]
WHAT COULD IT POSSIBLY BE

**Comment by nuthinking** [comment]
<img width="290" alt="screen shot 2018-04-23 at 13 47 14" src="https://user-images.githubusercontent.com/163635/39124750-deca3030-46fc-11e8-8be4-0cb5e7a266aa.png">

**Comment by Marak** [comment]
AMAZING FIND

**Comment by nuthinking** [comment]
Happy to help.

**Comment by Marak** [comment]
DUPLICATE https://github.com/Marak/faker.js/issues/585

WILL NOT FIX OR MAKE ANY NEW RELEASES UNTIL #583 #604 #621 RESOLVED

SORRY MY CAPSLOCK KEY IS STUCK
