### ISSUE TITLE
faker.date.soon is not a function

### ISSUE THREAD

**Issue by embiem** [Marak/faker.js#639]
I'm running faker v4.1.0, and the faker.date.soon() function is missing there.

**Comment by mBeierl** [comment]
OK, I just saw that it's actually new in the master branch but has not been released yet.

Sorry for this quick-shot issue. It's rare that the doc's are up-to-date ahead of the release ;-)

**Comment by niwrA** [comment]
I got the same error in typescript - seems that the types define it but the function is not there yet ... strange. Will continue to investigate.

**Comment by asap** [comment]
Any ETA on when `soon` will be released?

**Comment by MKRazz** [comment]
Hopefully `soon`.

**Comment by eddybrando** [comment]
Any real roadmap tho? Because the last npm release was 2 years ago.

Otherwise I'll consider forking master and releasing a parallel updated npm package.

**Comment by akhoury** [comment]
do it

**Comment by hudhaifahz** [comment]
A good alternative - use decimal places on the future function:
`const dueAt = faker.date.future(0.1,createdAt)`

**Comment by wgrabowski** [comment]
Headless Chrome on Jenkins stuck on this without any error, so this was a big trouble for me, since this was on build verifying PR in Bitbucket. @Marak are you planning to update npm package to fix this error?

**Comment by Ricardonacif** [comment]
We want that feature :D 💃

**Comment by gaspardip** [comment]
Just use `recent` with negative argument.

`recent(-1)`

**Comment by olaven** [comment]
The case of @niwrA still holds. 🙁 

Is this planned for release soon?
If not, should it be removed from the type definitions?

**Comment by DmitryEfimenko** [comment]
@Marak, any word on this?

**Comment by sujeet-agrahari** [comment]
What a wonderful package by careless devs. Issue was created two years ago still not fixed. Kudos to the devs.

**Comment by loremaps** [comment]
I believe this is resolved after `v5.0.0` release and can be closed.

**Comment by Marak** [comment]
This should be resolved with the new published version.

Please let us know if it's still not working.

Thanks!
