### ISSUE TITLE
Canadian Postal Code 

### ISSUE THREAD

**Issue by vkyt** [Marak/faker.js#640]
Noticed an issue with a generated en_CA postal code starting with W.  (i.e, W9N6A9)
This is an invalid postal district; please consider using only valid district for the leading letter when generating random postal code.

https://en.wikipedia.org/wiki/Postal_codes_in_Canada#Components_of_a_postal_code

**Comment by 07Gond** [comment]
Hi @Marak 
I just send a PR for this.
I also added the fr_CA postal codes locales.
