### ISSUE TITLE
LoremPixel is down. Should there be a switch to a different image faker?

### ISSUE THREAD

**Issue by robert-j-webb** [Marak/faker.js#641]
https://github.com/Marak/faker.js/blob/e2305d76d7c69134ab773127a4e6e4e82fab23f3/lib/image.js#L45

Do the maintainers want a PR that switches this URL to something else?

**Comment by gggeek** [comment]
Do you have any candidates in mind ?

**Comment by robert-j-webb** [comment]
Lorem Flickr looks alright? https://loremflickr.com/

**Comment by gggeek** [comment]
Nice. I have seen that lorem picsum also has an almost-same api as lorempixel

**Comment by robert-j-webb** [comment]
Yeah, it would just be a switch of the domain, so no real work. I did a little bit of research on lorem Flickr and it looks like it’s free and all they have is a paypal link, no advertising or anything.

**Comment by robert-j-webb** [comment]
Actually I totally take back what I said about loremFlickr, we should switch to https://placekitten.com/420/320

Alternatively, anything from this list should be fine: https://www.johanbostrom.se/blog/the-best-image-placeholder-services-on-the-web

**Comment by armadillojim** [comment]
FWIW, there's a pull request open at #398 to add additional image services.  However, it hard-codes different methods for different providers, and could stand to be refactored a bit.  If you could pick up the gauntlet, that'd be great!  At the same time, you could add loremFlickr, placekitten, and the others from johanbostrom.se's list.

**Comment by robert-j-webb** [comment]
Hmm I could look into it but that PR looks pretty massive! I'll look more closely this weekend.

**Comment by microvnhaxor** [comment]
+1. 

In my location vietnamese http://lorempixel.com alway down

**Comment by Marak** [comment]
PR #398 looks like the right solution.

If anyone could help review this PR it would help.

It would probably also be a good idea if we could use Github as provider through their CDN.

**Comment by Marak** [comment]
If anyone has additional input on this issue or PR #398 please let us know.

We'll be resolving this soon.

**Comment by mouafa** [comment]
I think it's time to move to another service or allow the user to select from different available services.
in both cases, PR #398 status should be resolved.

**Comment by dasDaniel** [comment]
for the time being, I'm using

```js
{
  image: 'https://picsum.photos/500/320/?image='+faker.random.number(1084),
}
```

which allows me to have repeatable results with `faker.seed()`, however, I noticed that some ids are missing on picsum.photos

**Comment by masiamj** [comment]
@Marak Any updates on this? Still looking for community support or are we ready on #398 ?

Thanks!

**Comment by mschipperheyn** [comment]
lorempixel is down (pinging from São Paulo Brazil). Service was spotty for the last week or so, and now it seems down.

**Comment by jrgreene** [comment]
It's down for me too.

**Comment by lcswillems** [comment]
lorempicsum is very slow. Could `https://picsum.photos/ ` be used instead in the API?

**Comment by PatricNox** [comment]
@Marak bump

**Comment by duxor** [comment]
Looks like DDoS attack :D

**Comment by saschaeggi** [comment]
+1

**Comment by fjbarrett** [comment]
Personally, I like placeimg.com. It also shares the same url structure as lorempixel.com, which makes things easy. I just made a new pull request with the change.

**Comment by mtuzinskiy** [comment]
Any updates on this? It's still down :slightly_smiling_face:

**Comment by Marak** [comment]
@mtuzinskiy -

Lorempixel should have been replaced as the default image provider a while back. You shouldn't get any URLs from Lorempixel website unless you explicitly ask Faker for LoremPixel.
