### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by irving2delgado** [Marak/faker.js#642]
this is the error received when attempting to install on cloud9 ide

npm ERR! Linux 4.9.80-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.2/bin/npm" "install" "faker"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! file /home/ubuntu/workspace/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'm' at 5:4
npm ERR!   "main": "server.js",
npm ERR!    ^
npm ERR! File: /home/ubuntu/workspace/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by Marak** [comment]
This looks like an issue with your local system or `package.json`, not an issue with faker.

Try updating to latest `node` and `npm` or trying to install on another system.

**Comment by irving2delgado** [comment]
ok thanks.
