### ISSUE TITLE
How to use it on angular

### ISSUE THREAD

**Issue by noyessie** [Marak/faker.js#650]
How to use faker in angular 5 /ionic environment.

**Comment by noyessie** [comment]
thank. It is very good library. I Like....

**Comment by FloNeu** [comment]
I like it very much too... kudos to the developer ^^

**Comment by ecolara3** [comment]
Just a heads up, installing Faker via the commands 

```
npm install faker --save
npm install @types/faker --save
```

caused issues with two of my napa dependencies. For some reason twitter-bootstrap-wizard and jquery.flot.animator are removed, well the files are removed in node_module directories. Not sure how or why this is happening, but legit the only reason I cannot use it.

**Comment by funder7** [comment]
I would save `@types/faker` in devDependencies maybe, what do you think?
