### ISSUE TITLE
Add git faker support

### ISSUE THREAD

**Issue by danielleadams** [Marak/faker.js#659]
I'm curious if anyone thinks it would be useful to add git support in the faker and/or internet API. Off the top of my head, useful methods would be for branch names, commit message, commit SHA, short SHA.

Note: I think all of these can be generated with other faker APIs, but it would also be nice to explicitly have support.

**Comment by Marak** [comment]
Interesting.

Is this something you require for actual work or is it just an idea? I'm curious what the potential use cases are for generating fake git data.

Regardless, this doesn't seem like it would require much code so feel free to start a PR and we can review.

**Comment by Marak** [comment]
Sounds good. Might make sense to create a new faker module `git`, or maybe put the functions in an existing module? Use your best judgement and we can sort it out in the PR.

Thanks!

**Comment by Marak** [comment]
Resolved with #662
