### ISSUE TITLE
Issue on name.firstName and name.lastName for Chinese locale

### ISSUE THREAD

**Issue by hs749** [Marak/faker.js#660]
Hello,
I really appreciate that faker.js supports localization. There are two Chinese locales supported: '**zh_CN**' and '**zh_TW**'.
And I did some quick testing on faker's API methods: name.firstName &  name.lastName, it seems that first name and last name generated by faker.js are reversed **incorrectly**, i.e. Chinese first name is generated by name.lastName while Chinese last name is generated by name.firstName.
The following is the three-line source code for the testing under node v8 environment:
&nbsp;&nbsp;&nbsp;var faker = require('faker/locale/zh_TW');
&nbsp;&nbsp;&nbsp;for (var i = 0; i < 10; i++)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; console.log(\`last name: ${faker.name.lastName()} <===> first name: ${faker.name.firstName()}\`);
And the following was the output:
last name: 遠航 <====> first name: 侯
last name: 立誠 <====> first name: 丁
last name: 苑博 <====> first name: 夏
last name: 耀傑 <====> first name: 賈
last name: 文昊 <====> first name: 邱
last name: 鵬濤 <====> first name: 程
last name: 鴻煊 <====> first name: 吳
last name: 君浩 <====> first name: 覃
last name: 峻熙 <====> first name: 黃
last name: 峻熙 <====> first name: 白

Thanks,

Hua

**Comment by hs749** [comment]
I took a quick look at the GitHub source code. The fixes on this issue might be just rename the files:
first_name.js  renamed to last_name.js
last_name.js   renamed to first_name.js
under this folder: https://github.com/Marak/faker.js/tree/master/lib/locales/zh_CN/name

**Comment by hs749** [comment]
And also this folder:
https://github.com/Marak/faker.js/tree/master/lib/locales/zh_TW/name

**Comment by Marak** [comment]
你好。 我不擅长说或读中文。我可能很难验证问题。

( switching back to english ) 

It would really help if you could do any of the following:

 - Identify the original commits which caused this break
 - See if any other users have reported this issue
 - Have another native chinese speaker comment here to verify the problem

I'm glad to fix the issue but I'll need a bit more verification before making the change.

**Comment by Spiderpowa** [comment]
Hi Marak,

I'm a native Chinese speaker and I can confirm this issue. The first name and last name of both Chinese locale (zh_TW and zh_CN) should be fixed as mention by @hs749

**Comment by Marak** [comment]
Thank you @Spiderpowa and @hs749 

Should be resolved with #821 and will be included in next release.
