### ISSUE TITLE
Random word (singular) sometimes returns more than one word

### ISSUE THREAD

**Issue by jamesbrucepower** [Marak/faker.js#661]
Since there are two methods .random.word() and .random.words() I would expect the first one to only include a singular word, but it sometimes generates more than one word.

**Comment by Marak** [comment]
Any idea why this is the case?  A PR would be welcomed.

**Comment by philg-ygt** [comment]
An example would be when the randomly selected word method is `commerce.productName` as that method returns a string of three words.

**Comment by Marak** [comment]
Probably the easiest way to patch the `random` module is to split the returned value from `random.word` on the space character and then select a random item from the created array.

This way we can use multiple api methods internally for generating words and guarantee only a single word in returned.

The PR for this should be relatively easy if anyone wants to try.

**Comment by twk-b** [comment]
still not resolved... ever 3-4 times we get what always seems to be a 3 word combo

**Comment by cyberprodigy** [comment]
Anyone else wasting time on this?
`faker.random.word().split(" ")[0]`

**Comment by sleonardoaugusto** [comment]
Just use `faker.lorem.word()`
