### ISSUE TITLE
faker.date.between(date1, date2) not working properly

### ISSUE THREAD

**Issue by wojciechiwanicki** [Marak/faker.js#693]
hi, 
when i write 
`faker.date.between('today', '+30d')`
it's working properly. However, when I write two fixed dates: for example 
`print(rand_date('2018-10-10', '2019-10-25'))`,
 it throws an error:
`    raise ParseError("Can't parse date string `{}`.".format(value))
faker.providers.date_time.ParseError: Can't parse date string 2018-10-10`
Am I missing something, or is it an issue?
thanks

**Comment by batisteo** [comment]
This could be closed as the OP should open an issue on https://github.com/joke2k/faker which is the Python equivalent of this lib.
