### ISSUE TITLE
What's wrong with it?

### ISSUE THREAD

**Issue by lcherone** [Marak/faker.js#736]
Redacted

**Comment by lcherone** [comment]
No I dont, Just making a point that there is better names especially when it randomly picks `Little Gaylord` in a business setting which is not good.

Look at the original edit, and should let reply instead of locking it.

**Comment by lcherone** [comment]
https://www.urbandictionary.com/define.php?term=Gaylord

**Comment by matthewtrask** [comment]
Plenty of businesses use this name as well. Off the top of my mind is the Gaylord Opryland Resort and Conference center in Nashville, Tennessee.

**Comment by mastermatt** [comment]
The Gaylord Rockies Resort and Convention Center just opened in Denver.

**Comment by lcherone** [comment]
Censorship lol

**Comment by Marak** [comment]
@lcherone 

I have banned you from further contributing to this repository.

This is a place for software development and not political or ideological debates. 

Please feel free to take your contributions elsewhere.
