### ISSUE TITLE
Integrate thispersondoesnotexist.com for realistic portrait photos (?)

### ISSUE THREAD

**Issue by tripu** [Marak/faker.js#755]
Just a wild idea.

If it's feasible to leverage [thispersondoesnotexist.com](https://www.thispersondoesnotexist.com/) somehow, that'll give us good random portraits and profile images of people&hellip;

**Comment by simonfranz** [comment]
sadly the site seems to be offline now

**Comment by blubbll** [comment]
> sadly the site seems to be offline now

https://www.thispersondoesnotexist.com/
https://www.thispersondoesnotexist.com/image <-- current output
https://isitup.org/www.thispersondoesnotexist.com <-- is it?
https://downforeveryoneorjustme.com/thispersondoesnotexist.com

**Comment by tripu** [comment]
:mega:  
**Anyone interested in this particular feature (and in ongoing development of Faker in general)**:  
this is now part of my own fork.

* GitHub project: [`tripu/faker.js`](https://github.com/tripu/faker.js)
* Alternative npm package: [`phaker`](https://www.npmjs.com/package/phaker)
