### ISSUE TITLE
random.float is not a function

### ISSUE THREAD

**Issue by ckiss** [Marak/faker.js#761]
Hey there,

Using `faker.random.float` throws error (not a function) although it is described in the documentation.

Am I supposed to be using `random.number` with some parameters to get the same effect? If so, I think `float` should be removed from documentation.

**Comment by macrozone** [comment]
can confirm, stopped working

**Comment by chffUA** [comment]
Seems to work for me?

    > console.log(faker.random.float())

    < 26597.24

    > console.log(faker.random.float(0.1))

    < 5193.8

Can you show the relevant code snippet?

**Comment by ckiss** [comment]
@chffUA http://jsfiddle.net/jca5nqpr/ here is a code snippet. Locally I was using version 4.1.0. I also checked the lib/random.js file and I couldn't find the float function.

**Comment by Marak** [comment]
https://github.com/Marak/faker.js/blob/d3ce6f1a2a9359574e7f31f14d4901648047c45a/test/random.unit.js#L102

**Comment by ckiss** [comment]
@Marak I can't argue with your snippet, but for me it doesn't work. https://runkit.com/ckiss/5c8906b6d09cd400123f34dd here is another example. You can see in there it's using version 4.1.0. Maybe there are some issue with your npm bundle, I can't say. Let me know if you need something else.

**Comment by Marak** [comment]
Obviously, it's on master and not in the release.
