### ISSUE TITLE
Don't put unreleased stuff into documentation

### ISSUE THREAD

**Issue by ckiss** [Marak/faker.js#762]
@Marak I pointed out in my initial issue that `random.float` is specified in the documentation. I don't think it should be there if not released, that way nobody's precious time is wasted.

I appreciate the work you guys do on faker, nice tool! 👏 
Cheers!

PS: a little screenshot with the docs
![Screenshot 2019-03-13 at 15 45 48](https://user-images.githubusercontent.com/1004239/54283649-2094fa00-45a7-11e9-82b3-99e0f92accc9.png)

**Comment by Marak** [comment]
Thanks for your feedback. This is helpful.
