### ISSUE TITLE
error installing faker 

### ISSUE THREAD

**Issue by bootpb99M** [Marak/faker.js#765]
when i enter the npm install --save faker in cmd
i face a bunch of error and warning messages and after that starting my react application also throws errors that i do not know what they mean .
i tried cloning the faker library to my node-modules directory and i faced error that says : cannot resolve faker .
what can i do ????
please help me.

**Comment by Marak** [comment]
The build is currently reporting [100% passing with 99% coverage](https://travis-ci.org/Marak/faker.js).

Most likely there is some issue wrong with your local environment?

No one is going to be able to help you without more information such as the logs or errors you are seeing.

**Comment by bootpb99M** [comment]
these are errors . first errors are occuring during the installation of faker by running the command "npm install --save faker" after that when i try again with this command there is no error or warning .
but after this installation i face errors when starting my react project
<img width="674" alt="1" src="https://user-images.githubusercontent.com/48807254/54883152-3d231300-4e80-11e9-9b1e-66c300c4b432.PNG">
<img width="671" alt="2" src="https://user-images.githubusercontent.com/48807254/54883153-3dbba980-4e80-11e9-9984-d15672d8ca09.PNG">
<img width="672" alt="3" src="https://user-images.githubusercontent.com/48807254/54883154-3dbba980-4e80-11e9-92d4-8d33bc0414a4.PNG">
<img width="666" alt="4" src="https://user-images.githubusercontent.com/48807254/54883155-3dbba980-4e80-11e9-96db-b6a0a85dc5fb.PNG">
<img width="668" alt="5" src="https://user-images.githubusercontent.com/48807254/54883156-3e544000-4e80-11e9-8d6b-a834e71280aa.PNG">
