### ISSUE TITLE
error with installing faker.js

### ISSUE THREAD

**Issue by bootpb99M** [Marak/faker.js#766]
these are errors . first errors are occuring during the installation of faker by running the command "npm install --save faker" after that when i try again with this command there is no error or warning .
but after this installation i face errors when starting my react project
<img width="674" alt="1" src="https://user-images.githubusercontent.com/48807254/54883575-680f6600-4e84-11e9-85cb-e6cfa3c63c40.PNG">
<img width="671" alt="2" src="https://user-images.githubusercontent.com/48807254/54883576-68a7fc80-4e84-11e9-95f6-d64b35965a6a.PNG">
<img width="672" alt="3" src="https://user-images.githubusercontent.com/48807254/54883577-68a7fc80-4e84-11e9-8b6f-84d055944b4c.PNG">
<img width="666" alt="4" src="https://user-images.githubusercontent.com/48807254/54883578-69409300-4e84-11e9-908a-a9b688665551.PNG">
<img width="668" alt="5" src="https://user-images.githubusercontent.com/48807254/54883579-69409300-4e84-11e9-892e-54193aa487e6.PNG">

**Comment by verde79** [comment]
I just had the same problem and found Marak suggesting to update the npm version (for another issue but I tried it anyway), anyways, mine works now, the package.json has been updated to include faker.

To update npm:
`sudo npm install npm -g`

Try installing faker again:
`npm install --save faker`
