### ISSUE TITLE
Add comma to thousands for faker.finance.amount 

### ISSUE THREAD

**Issue by chrisyap** [Marak/faker.js#767]
Is there a way to return 6,234.32 with a comma when using finance amount?
faker.finance.amount(6000, 6400, 2)

**Comment by sbaechler** [comment]
The formatting is locale specific.

You can use `number.toLocaleString()`. (Requires Node > 9 with i18n extension.)

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by Marak** [comment]
It might be nice if we could add this as a simple argument `autoformat` to `finance.amount`.

**Comment by strobelt** [comment]
Can I take care of this? Seems like a simple enough change to the `finance.amount` method

**Comment by Marak** [comment]
Thanks for this information @chrisocast @schlpbch 

Thank you for your contributions @strobelt.

This should now be resolved on `master` with #1015 

Closing.
