### ISSUE TITLE
After setting locale to en_US still getting non US area codes

### ISSUE THREAD

**Issue by tomatobrown** [Marak/faker.js#770]
I'm not sure I'm defining my locale correctly, I've tried both
`const faker = require('faker/locale/en_US');`
and just
`faker.locale = 'en_US'`

With both approaches when I execute `faker.phone.phoneNumber()` I'm getting area codes that do not exist inside of `lib/locales/en_US/phone_number/area_code.js`

**Comment by Marak** [comment]
I'm going to guess it's pulling data from the `en` locale ( which is also the default fallback locale for all other localities )

see: https://github.com/Marak/faker.js/tree/master/lib/locales/en

**Comment by tomatobrown** [comment]
Is there no way to just get US area codes then?

**Comment by monkpit** [comment]
I'm having the same issue - Getting invalid area codes like '059' or '191' which are not in `area_code.js` for en_US locale. Same as OP, I am requiring `faker/locale/en_US`.

Any advice on how to avoid this issue?
