### ISSUE TITLE
Add support finance.transactionDescription

### ISSUE THREAD

**Issue by WuglyakBolgoink** [Marak/faker.js#773]
Hallo guys,

thank you for a great library!

In case of my project, it was a very helpful to have for example turnover description. In this case `transactionDescription` can generate some texts like this: https://github.com/candu/quantified-savagery-files/blob/master/Financial/mint-bubbles/transactions.csv

**Comment by Marak** [comment]
@WuglyakBolgoink -

This seem likes a good idea!

Could probably be created with not many lines of code.

Will accept a PR.

**Comment by drsherlock** [comment]
Hi,
Would like to give this a try.

**Comment by ashishra0** [comment]
hey @WuglyakBolgoink can you elaborate more on this? Thanks!

**Comment by Marak** [comment]
Resolved with #824
