### ISSUE TITLE
Cannot save random.uuid as function and call it later

### ISSUE THREAD

**Issue by SrdjanCosicPrica** [Marak/faker.js#780]
I'm trying to create a factory for my classes.
I have an object which defines how certain values should be randomized if they are not overriden.
example
```
randoms = {
    id: faker.random.uuid
}

export function getObject(options) {
    const obj = {};
    const keys = Object.keys(randoms);
    for (const key of keys) {
        obj[key] = options[key];
        if (typeof obj[key] === "undefined") {
            obj[key] = randoms[key]();
        }
    }
}
```

But for the `random.uuid` I get
```
TypeError: self.number is not a function
      
      at replacePlaceholders (node_modules/faker/lib/random.js:93:29)
          at String.replace (<anonymous>)
      at Random.uuid (node_modules/faker/lib/random.js:97:31)
```
and I don't know why but `this` in the `uuid` function does not have `this.number`. 
This works fine for other functions that do not depend on `this`.

Can be quickly tested by just doing
```
const method = faker.random.uuid;
console.log(method());
```

**Comment by SrdjanCosicPrica** [comment]
I made a quick modification in my node_modules and this is fixed with this change on line in random.js 89
```
this.uuid = () => {
```

**Comment by Marak** [comment]
I checked `master` and don't see any instances of the word `self` in https://github.com/Marak/faker.js/blob/master/lib/random.js.

This issue hasn't existed for some time. Please make sure to use the latest version of faker.

**Comment by SrdjanCosicPrica** [comment]
Well latest version is 4.1.0, which is the one I am using. 4.1.0 was released 2 years ago. Maybe those changes in master have not been released? @Marak
