### ISSUE TITLE
Generating real email addresses

### ISSUE THREAD

**Issue by spam-man** [Marak/faker.js#781]
Some email addresses generated by faker.internet.email() are not fake, but real addresses. Is this the expected behavior?

If so, there should be a warning to not use this method while testing email applications, otherwise tests can end up sending emails to real people.

**Comment by Marak** [comment]
I'm not sure how else you would reasonably expect this to work.

If you send out an SMTP message to an email address at a host you don't control ( like `localhost` ) you should expect something to happen.

This is how email works. If you don't want to send out emails, then don't send out emails.

**Comment by spam-man** [comment]
Sure, they should be proper email addresses... but not belonging to real people, I suppose. 

For instance, using gmail.com, many of the addresses will probably belong to real people. 

I totally agree with what you say "If you don't want to send out emails, then don't send out emails."

But at least a warning to users would be in order, because people may suppose they are generating *fake* addresses, not *real* ones...

**Comment by spam-man** [comment]
I would expect faker to use fake domains instead of real ones.

**Comment by spam-man** [comment]
This a discussion of this same problem in the faker ruby gem, raised by someone who ends up receiving test emails on their end:
https://github.com/stympy/faker/issues/685

**Comment by Marak** [comment]
What exactly is a fake domain?

**Comment by spam-man** [comment]
In this case, one that looks like a valid domain, but doesn't exist. Like gmail.test, or example.com, or a <random string>.net

**Comment by Marak** [comment]
If you want an email generated for a specific domain, you can use the `provider` argument to `faker.internet.email`.

see: https://github.com/Marak/faker.js/blob/master/lib/internet.js#L31

Just like the other project you linked, we are not going to make any changes to email generation to prevent it from making "real" email addresses. Same exact answer for telephones numbers, addresses, names, social security numbers, credit card numbers.

Locking issue.
