### ISSUE TITLE
Email a bad format after @

### ISSUE THREAD

**Issue by gothraven** [Marak/faker.js#794]
Email shouldn't contain `_` after `@`

**Comment by Marak** [comment]
That shouldn't happen. Can you provide example with random seed which resulted in that result?

**Comment by gothraven** [comment]
Sorry it was kinda test_cafe's issue (and also my bad), i faker.created an email and testcafe wrote it backwards, which created the issue and i thought it was an email issue until I hard coded an email to see it after written backwards.
