### ISSUE TITLE
Country gets reset to random but other fields are preserved

### ISSUE THREAD

**Issue by jpxrc** [Marak/faker.js#806]
I apologize if this isn't a bonafide issue, but it's a little annoying having all of the fields (e.g. name) getting preserved after closing the browser except for the country, that then gets reset to 'random' each time. 

The issue is that you then get a bunch of random names in foreign alphabets. Not a huge issue but it would be nice if country selection gets preserved too for faster a workflow. I'm also using this as a chrome extension. Any plans to fix this or is this intended by design?

**Comment by Marak** [comment]
???

**Comment by jpxrc** [comment]
> ???

Ah sorry I just realized you're not the one maintaining the chrome extension so that's probably an error on their end. I apologize for the inconvenience.
