### ISSUE TITLE
system.fileExt is slow

### ISSUE THREAD

**Issue by makepanic** [Marak/faker.js#822]
Hi, thanks for this great package.

I found some generators to be slow and looking at the source there might be ways to optimize them.

## `fileExt`

https://github.com/Marak/faker.js/blob/master/lib/system.js#L109

This generates the list of all mime extensions for each invocation. This can probably be memoized to avoid doing it again after a repeated call.
In my test it created a string array with >1k entries for each invocation.

This also means any generator, which consumes `fileExt`, e.g. `fileName` computes it again.

![20190911-090920](https://user-images.githubusercontent.com/1205444/64677800-99064600-d478-11e9-939d-8690c2b6ec80.png)

Are you open for PRs which try to tackle some performance issues?

**Comment by Marak** [comment]
@makepanic -

> Are you open for PRs which try to tackle some performance issues?

Yes.
