### ISSUE TITLE
how to generate patronymic?

### ISSUE THREAD

**Issue by sevaTechoPark** [Marak/faker.js#827]

**Comment by ilyakanevsky** [comment]
`const faker = require('faker');

const getMiddleName = function (gender) {
	if (
			   typeof faker.definitions.name.male_middle_name !== 'undefined'
			&& typeof faker.definitions.name.female_middle_name !== 'undefined'
	   ) {
		if (typeof gender !== 'number') {
			gender = faker.random.number(1);
		}
		return faker.random.arrayElement(faker.locales[faker.locale].name[gender === 0 ? 'male_middle_name' : 'female_middle_name']);
	}
	return '';
};
`

**Comment by ilyakanevsky** [comment]
See also #713.

**Comment by IgorSharov** [comment]
In addition to @ilyakanevsky's answer.
Working with Typescript I came accross that there is no matchable field in `@types/faker`.
To use it with Typescript you might consider a workaround:
1. Create a new file to make your own custom faker **(faker.js):**
```
import faker from "faker/locale/ru"; // -> for russian locale

const middleName = function(gender) {
  if (
    typeof faker.definitions.name.male_middle_name !== "undefined" &&
    typeof faker.definitions.name.female_middle_name !== "undefined"
  ) {
    if (typeof gender !== "number") {
      gender = faker.random.number(1);
    }
    return faker.random.arrayElement(
      faker.locales[faker.locale].name[
        gender === 0 ? "male_middle_name" : "female_middle_name"
      ]
    );
  }
  return "";
};

export default { ...faker, name: { ...faker.name, middleName } };
```
2. Then import your custom faker and needed propierty will be there.
```
import faker from "./faker";
const gender = faker.random.number(1);
const patronymic = faker.name.middleName(gender);
console.log(patronymic);
```

**Comment by IgorSharov** [comment]
In addition to @ilyakanevsky's answer.
Working with Typescript I came accross that there is no matchable field in `@types/faker`.
To use it with Typescript you might consider a workaround:
1. Create a new file to make your own custom faker **(faker.js):**
```
import faker from "faker/locale/ru"; // -> for russian locale

const middleName = function(gender) {
  if (
    typeof faker.definitions.name.male_middle_name !== "undefined" &&
    typeof faker.definitions.name.female_middle_name !== "undefined"
  ) {
    if (typeof gender !== "number") {
      gender = faker.random.number(1);
    }
    return faker.random.arrayElement(
      faker.locales[faker.locale].name[
        gender === 0 ? "male_middle_name" : "female_middle_name"
      ]
    );
  }
  return "";
};

export default { ...faker, name: { ...faker.name, middleName } };
```
2. Then import your custom faker and needed property will be there.
```
import faker from "./faker";
const gender = faker.random.number(1);
const patronymic = faker.name.middleName(gender);
console.log(patronymic);
```

**Comment by Marak** [comment]
Thank you @IgorSharov @ilyakanevsky for assisting.

#713 has been merged to `master` and should help

If anyone who is native Russian speaker could please review #713 for accuracy, that would be appreciated.
