### ISSUE TITLE
[Feature Request] add support to generate random floating point numbers

### ISSUE THREAD

**Issue by blackshady** [Marak/faker.js#829]
Hi there, would it be possible to add support to generate random floating-point numbers?

I will suggest modifying the options parameter passed when `faker.random.number` is called to support floating point numbers. Thanks!

**Comment by JoshM1994** [comment]
+1 on this

In the meantime, I'm using this alternative:

Precision as a floating point
`random.number({min: 60, max: 65, precision: 0.04})     // --> 62.92`
(note: make sure you use something which is nice in binary [for your precision] to avoid super long floating points (see: https://0.30000000000000004.com/) or do a `Math.round` at the end

**Comment by samir-araujo** [comment]
Maybe wouldn't it be better to just use `random.float` that is already supported?

**Comment by mastermatt** [comment]
This feature was added as `random.float` in Aug 2017 https://github.com/Marak/faker.js/commit/56aa8121f254482ae2f200605402c9d4eb917abe, however, there hasn't been a published version since then.

**Comment by Marak** [comment]
Resolved.
