### ISSUE TITLE
Some IBAN are invalid

### ISSUE THREAD

**Issue by mickaelchanrion** [Marak/faker.js#846]
Hey 👋
It seems that some generated IBAN are invalid. Especially the ones for Azerbaijan:
- AZ61042647281602130500843080
- AZ70471180928911231507343770

I'm using [ibantools](https://www.npmjs.com/package/ibantools) to validate iban on my frontend app, and it gives invalid result for those above.

I also checked using this website: https://bank.codes/iban/validate/
Same result... :/ 

EDIT: 
It seems to be the same for some BIC:
- OMPUCPT1MAB
- RXTICPF1475
- LVGACSQ1

**Comment by Moosh-be** [comment]
hello @mickaelchanrion My PR would reslove this issue.
If you can try my PR on your side...
