### ISSUE TITLE
en_ZA locale not available

### ISSUE THREAD

**Issue by ion-willo** [Marak/faker.js#849]
Hi,

I recently installed faker for node using `npm i faker`, and even though I see the en_ZA locale on the git repo, the installed package doesn't have it available. Is there an update pending or is there a way for me to bring in the locale temporarily under my own code tree?

**Comment by KeeganFerrett** [comment]
Ran into the same problem with locales so figured I'd just leave my solution here to help the next person who encounters this problem.

Simply install the package via the repo using `npm i git+https://github.com/Marak/faker.js`.

It seems a number of locales were added but the library was never updated on npm.
