### ISSUE TITLE
Any way to filter out profanity?

### ISSUE THREAD

**Issue by vgjenks** [Marak/faker.js#851]
Generated an image URL w/ this value:

https://s3.amazonaws.com/uifaces/faces/twitter/fuck_you_two/128.jpg

All good and fine...unless you're generating fake data for clients to preview your APIs.

Seems like it'd be a good idea to be able to globally filter out any sort of profanity, or just not allow it through at all, to begin with?

**Comment by Marak** [comment]
It looks like `fuck` is in the name of some of the free image avatars provided to the project. 

Not really an intentional addition.

If anyone wants to grep the codebase and remove the profanity I will merge the request.
