### ISSUE TITLE
random.float is not a function #761

### ISSUE THREAD

**Issue by uwinkler** [Marak/faker.js#852]
This is  a dublicate of #761, but I cant re-open it or  add an comment.

The problem seems to be still around.

I am using version 4.1.0 and I get the same error     

`faker.random.float is not a function`

**Comment by ceednee** [comment]
Version 4.1.0 was created 2 years ago.
Why can't we have the latest version from npm?

**Comment by exit490** [comment]
I'm having same problem.

**package.json**
` "devDependencies": {
    "eslint": "latest",
    "eslint-plugin-promise": "latest",
    "jest": "latest",
    "rewire": "^4.0.1",
    "faker": "4.1.0"
  },
`
I'm trying within my tests with jest.js

**my_test.js**
`const Faker = require('faker');

test('faker random float', () => {

    const randomLessOffer = Faker.random.float(1);
    console.log(randomLessOffer)

});`

**Comment by Marak** [comment]
Locking duplicate issue.
