### ISSUE TITLE
faker.random.number() not working 

### ISSUE THREAD

**Issue by RemigiusL** [Marak/faker.js#854]
While using faker in automation testing all the faker components working fine by reading the testData from the excel sheet but when I call the **faker.random.number()** it gets failed. Why it happened, could help me out?

**the error was, 
The "text" argument is expected to be a non-empty string, but it was number.**

Also following with my [testcafe ](https://devexpress.github.io/testcafe/documentation/getting-started/)automation code:
***************
import { Selector } from 'testcafe';
import faker from'faker';

fixture`A set of examples that illustrate how to use TestCafe API`
    .page`http://devexpress.github.io/testcafe/example/`;

const developerName = Selector('#developer-name');
//var randomName = faker.random.number();

test('How to type text into an input (t.typeText user action)', async t => {
    await t
   
        .typeText(developerName, faker.random.number())
        .typeText(developerName, 'Paker', { replace: true })
        .typeText(developerName, 'r', { caretPos: 2 })
        .expect(developerName.value).eql('Parker');
        
});
***************

**Comment by lukebatchelor** [comment]
The answer is in the error message right? 

> The "text" argument is expected to be a non-empty string, but it was number.

`faker.random.number()` returns a number, not a string. TypeText needs a string.
Simply typecast it:

```
.typeText(developerName, String(faker.random.number()))
```

**Comment by RemigiusL** [comment]
@lukebatchelor 
Yes, It's working now. I don't see it. Thanks for your quick update 👍
