### ISSUE TITLE
Same Single Person/Instance consistent attributes/properties

### ISSUE THREAD

**Issue by Ammar11013** [Marak/faker.js#857]
All Attributes for Single instance / Person (having name, email etc consistent for one Person/Instance)))

e.g. fisrtName = Martin, lastName = Garrix, email = Martin_Garrix@example.com

**Comment by abnersajr** [comment]
Please, can you provide a clear description of what is your problem? Code example is welcome too.

**Comment by Ammar11013** [comment]
@abnersajr, issue resolved by passing firstName and lastName arguments in method: faker.internet.email(firstName, lastName) so i got email address according to firstName and lastName attributes, Thanks!
