### ISSUE TITLE
Is there a maintained fork?

### ISSUE THREAD

**Issue by IanVS** [Marak/faker.js#858]
I wanted to start using this package, but am concerned by the apparent abandonment.  I see that the last release of this project was nearly three years ago, and the discussion last year to release 5.0 seems to have stalled out.  Has anyone started a fork and published any of the changes that have been merged, or even cherry picked in any of the outstanding PRs?

**Comment by Marak** [comment]
Project is not abandoned, but is in a place where I am currently not spending much time on it.

Would be great if any developers representing a respected or known engineering organization could step up as maintainers.
