### ISSUE TITLE
date isn't working

### ISSUE THREAD

**Issue by SudarshanSaxena** [Marak/faker.js#860]
Im using this library in React and i tried using {props.date.past}} but its showing multiple errors.

**Comment by dbrn** [comment]
{faker.date.past()} is the correct syntax to use it

**Comment by nathanfoon** [comment]
@SudarshanSaxena, I believe `faker.date.past()` returns a [date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date); so you may need to call an additional method on it, like `.toDateString()`.
