### ISSUE TITLE
Is the most recent code in master published?

### ISSUE THREAD

**Issue by fijijavis** [Marak/faker.js#861]
NPM shows version 4.1.0 was published 3+ years ago.  
https://www.npmjs.com/package/faker

When is the next release scheduled to be published?

I'm seeing things in master that I'd like to use like `address.zipCodeByState`.

**Comment by therussiankid92** [comment]
Hi @Marak -- I'm interested in the latest aswell. How can we help?

**Comment by Marak** [comment]
Duplicate issue.
