### ISSUE TITLE
Add profile picture to userCard helper

### ISSUE THREAD

**Issue by jrock2004** [Marak/faker.js#862]
I really like the helper of `userCard` but I think a profile picture is missing. Any ways of getting that helper to add an image?

**Comment by Marak** [comment]
Yes.

**Comment by jrock2004** [comment]
@Marak are you closing this because you are going to implement this? Not understood why you closed this

**Comment by Marak** [comment]
?

You asked if there was a way to add this. I responded "yes".

If you have a feature request you should open a PR.
