### ISSUE TITLE
faker.seed is not putting out same data all the time

### ISSUE THREAD

**Issue by zedgell** [Marak/faker.js#874]
`faker.seed(1);`
 `faker.name.findName();`
 ` 'Amara Rath IV'`
   
  `faker.seed(1);`
  `faker.name.findName();`
  `'Aaliyah Champlin'`

It will repeat the same data about 70% of the time but other times it will put out different data. usually the data that is different is predictable but is not the same as the other 70%. This is being used in conjunction with json-schema-faker to create schemas to use as data. The problem is with all fields not just the `findName`

**Comment by Marak** [comment]
@zedgell Is this a faker issue?

**Comment by zedgell** [comment]
@Marak Not Necessarily. I had to declare it a little different that what json-schema-faker showed. 
the way I had to declare it was:
```Javascript
jsf.extend('faker', () => {
       const faker = require('faker');
       faker.seed(Number(seed));
       faker.custom = {
          date: year => {
              return faker.date.past(1, new Date(year, 0, 0))
       },
    };
    return faker;
});
```
vs before where I had it marked as:

```Javascript
jsf.extend('faker', () => {
    const faker = require('faker');
    faker.custom = {
        date: year => {
            return faker.date.past(1, new Date(year, 0, 0))
            },
    };
    return faker;
    });
faker.seed(Number(seed));
```

**Comment by Marak** [comment]
Thank you for the clarification! Hopefully this may help the next person.
