### ISSUE TITLE
Can i use faker with angularjs 1.7.9 to generate fully customized json structure?

### ISSUE THREAD

**Issue by OlaOssama** [Marak/faker.js#882]
How to use faker with angularjs 1.7.9?
And can i use it to generate something like:

```
{
    'Serial': {
      'builders': [
        {
          'StrategyContextModifiers': {
            'selectors': {
              'priceGap': {
                'formula': '<OwnPrice> + <OldPrice> / 2'
              },
              'priceGapUnit': {
                'value': 'absolute'
              },
              'targetPosition': {
                'formula': '1'
              }
            },
            'builder': {
              'PriceStep': {
                'priceSteps': ['1', '99'],
                'stepSelection': 'nextHigher',
                'builder': {
                  'TargetPosition': {}
                },
              }

            }
          }
        }
      ]
    },
    'version': '2'
  }
```

**Comment by samir-araujo** [comment]
Hello, @OlaOssama !

Faker is a module like any other library, so you can use in your app using `import faker from 'faker'` or `const faker = require('faker')`. Of course you can also access a specific locale if you wish.

About your JSON, which part of it would be dinamically generated with faker?

**Comment by OlaOssama** [comment]
> Hello, @OlaOssama !
> 
> Faker is a module like any other library, so you can use in your app using `import faker from 'faker'` or `const faker = require('faker')`. Of course you can also access a specific locale if you wish.
> 
> About your JSON, which part of it would be dinamically generated with faker?


Thanks for your reply, 
I would like to dynamicaly generate the whole JSON attached

**Comment by samir-araujo** [comment]
@OlaOssama ,

Looking at your JSON, I'm assuming that its actually an object and the values that you wish to randomize are the `OwnPrice` and `OldPrice` for the formula.

If that is correct, I've made a small Codesandbox example here: https://codesandbox.io/s/gracious-cloud-xchmq

Also if you prefer, here is the code:

```js
import faker from "faker";

const ownPrice = parseFloat(faker.commerce.price());
const oldPrice = parseFloat(faker.commerce.price());

const data = {
  Serial: {
    builders: [
      {
        StrategyContextModifiers: {
          selectors: {
            priceGap: {
              formula: ownPrice + oldPrice / 2
            },
            priceGapUnit: {
              value: "absolute"
            },
            targetPosition: {
              formula: "1"
            }
          },
          builder: {
            PriceStep: {
              priceSteps: ["1", "99"],
              stepSelection: "nextHigher",
              builder: {
                TargetPosition: {}
              }
            }
          }
        }
      }
    ]
  },
  version: "2"
};

console.log(data);
```

If its is not what you meant, could you please explain in more depth what you are trying to achieve?
