### ISSUE TITLE
[pt_BR] invalid URLs

### ISSUE THREAD

**Issue by gabrielmmontenegro** [Marak/faker.js#883]
Hi,

Thanks for the amazing work on this project.

I just wanna let you know that some of my tests are eventually breaking with invalid URLs when in ```pt_BR``` locale, which includes accents and spaces. 

Examples:

```
"https://júlio césar.info"
"http://vitória.br"
```

My project is running the latest version of faker: 4.1.0.

Best,
Gab

**Comment by Marak** [comment]
Resolved with #895
