### ISSUE TITLE
faker.finance.amount() returns a string

### ISSUE THREAD

**Issue by amartiuz** [Marak/faker.js#884]
Following the documentation it says: **Decimal number faker.finance.amount(min, max, decimal places) Random number between "min" and "max" including decimals to X digits.**

- **Expected behavior**: should return a **number**. ie: `122.12`
- **Current Behavior**: returns a **string**. ie: `"122.12"`

**Comment by Marak** [comment]
Should be resolved with #887 and will be included in the next release.

Thank you taking the time to report this @amartiuz
