### ISSUE TITLE
[Feature Request] Letter/Email opening/salutation and closings

### ISSUE THREAD

**Issue by rmgreenstreet** [Marak/faker.js#886]
It would be great if we could get something like `faker.email.salutation();` which would return some salutation like "Hey there, ", "Hi, ", "Greetings, ", "Guten tag", etc.

And then similar for `faker.email.closing();` something like "All the best, ", "See ya, ", "Yours, ", "Cordially, ", "Hasta la vista, baby, ", etc.

**Comment by Marak** [comment]
Sounds good!
