### ISSUE TITLE
Is it possible to generate random enum value with faker? 

### ISSUE THREAD

**Issue by 4ekki** [Marak/faker.js#901]
I'm using Typescript and sometimes need to pick a random enum value.

```
enum currencies {
  EUR = "EUR",
  USD = "USD",
  GBP = "GBP",
}

const randomCurrency = faker.random_value(currencies);
```

Is it possible to do the same via faker?

**Comment by Marak** [comment]
Faker has a `random` module which has several methods for generating and selecting random values. Please read the documentation before posting questions here.
