### ISSUE TITLE
Please add empty-guid predefined global variable

### ISSUE THREAD

**Issue by weitzhandler** [Marak/faker.js#905]
Much like the `guid` global variable, please add something like `empty-guid`, that generates an uinitialized guid: `00000000-0000-0000-0000-000000000000`, to be used for validation purposes.

Alternatives: copy-paste from [here](https://stackoverflow.com/a/48804617/75500).

Migrated from [here](https://github.com/postmanlabs/postman-app-support/issues/8407).
Thanks

**Comment by Marak** [comment]
I have gone ahead and generated an uninitialized  UUID you can use: `00000000-0000-0000-0000-000000000000`

Please let me know if that isn't sufficient.
