### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by pabrrs** [Marak/faker.js#910]
Hi,

I notice some methods described in `README` not exists in lib.

```
faker.date.soon
faker.finance.ethereumAddress
faker.random.float
faker.random.hexaDecimal
```

I've run this check using this script: https://repl.it/@abekroenem/LimpingRoughViruses

I'm using the last version published `4.1.0`

Can anyone help ?

**Comment by Marak** [comment]
Check `master` and not `npm` release.
