### ISSUE TITLE
change dummy image generator - lorempixel is dead

### ISSUE THREAD

**Issue by StartMeUpLille** [Marak/faker.js#935]
Hi
I wanted dummy cats pictures and I realize it uses lorempixel to get fake images.
Lorempixel seems dead, you should change the fake image provider

**Comment by nicko7i** [comment]
I tried it this morning.  Loempixel isn't dead, but it is very slow.  A random picture takes 20 - 40 seconds to load.

**Comment by Marak** [comment]
There has been a bit of work to improve the provider pattern and default provider for random images. Make sure to use the `master` version of faker here on Github.

I'll make sure to prioritize fixing the image providers, a few people have had issues.

**Comment by Marak** [comment]
Should be resolved in latest release.
