### ISSUE TITLE
Will there be a new published version soon?

### ISSUE THREAD

**Issue by cafesanu** [Marak/faker.js#937]
Hi!, I'm wondering when will there be a published version? I was trying to use random float, which is already in master, but just found out that the last published version was in Novermber 2017 according to this https://github.com/Marak/faker.js/releases/tag/v4.1.0.

Would be great to create a new version in npm with all the awesome improvements that have happened since then :)

Thanks!

**Comment by Marak** [comment]
It's being worked on.

Closing this issue because there are other issues already open for this.
