### ISSUE TITLE
US phone number generated incorrectly

### ISSUE THREAD

**Issue by akanksha4lal** [Marak/faker.js#939]
**Steps**
Install faker using yarn
Try generating US phone number : _faker.phone.phoneNumberFormat(1)_

**Expected**
The phone format for US should not start with 1

**Actual**
The phone number is generated starting with 1

Looks like the file  _lib/locales/en/phone_number/formats.js_ is incorrect yarn pkg 
[[https://yarnpkg.com/package/faker?files]]

**Comment by Marak** [comment]
We don't really understand the issue because US phone numbers can start a `1`.

If you can provide a failing test as a PR we are glad to review it.

Thanks!
