### ISSUE TITLE
Unable to create few fields

### ISSUE THREAD

**Issue by harikrishna-vadlakonda** [Marak/faker.js#940]
wanted to create a category of country and then would like to show output as mentioned fields and values
Country 
Name
Continent
Area (km2)
population in Millions 
Capital
Largest city    
Official languages  
Demonym(s)
Government

But could not able to find Continent,Area(specifically),population in Millions(specifically),Official languages,Demonym(s),Government fields in any of the mentioned APIs in faker library..

**Comment by Marak** [comment]
@harikrishna-vadlakonda -

Thank you for your feedback.

If you'd like to try coding it up, we will accept Pull Requests which add some or any of these mentioned functionalities.

Cheers!
