### ISSUE TITLE
faker.internet.email() may generate invalid email with other locales

### ISSUE THREAD

**Issue by clarmso** [Marak/faker.js#943]
When I'm trying to generate some email address under the "ja" locale, some email address are invalid.

To reproduce the issue, I use the browser's console from the demo page (https://rawgit.com/Marak/faker.js/master/examples/browser/index.html).  Here's the input and output:

```
console.log(faker)
VM599:1 Faker {locales: {…}, locale: "ja", localeFallback: "en", definitions: {…}, fake: ƒ, …}
undefined
faker.locale = "ja"
"ja"
faker.internet.email()
".2@gmail.com"
faker.internet.email()
"87@yahoo.com"
faker.internet.email()
"74@gmail.com"
faker.internet.email()
"74@yahoo.com"
faker.internet.email()
"_@gmail.com"
faker.internet.email()
"15@gmail.com"
faker.internet.email()
"_34@yahoo.com"
faker.internet.email()
".96@hotmail.com"
```

The email addresses that start with "." character are invalid.  Please see https://en.wikipedia.org/wiki/Email_address#Syntax for the details.

**Comment by clarmso** [comment]
If this is a legit issue, I could potentially open a PR to fix it.

**Comment by Marak** [comment]
@clarmso -

Thank you for bringing this to our attention.

If you are able to open a PR to resolve this it would be much appreciated.

Thank you.

**Comment by netochaves** [comment]
I open a PR for this, the same problem was happening with `ch` locales.  The problem was because of this regex: 
https://github.com/Marak/faker.js/blob/cb851b7656309e99ebbb61174f68d5e93e2ee147/lib/helpers.js#L28

This was removing the Japanese characters, so I just include them in the regex.
