### ISSUE TITLE
IBAN for Georgia not correct

### ISSUE THREAD

**Issue by christianbaumann** [Marak/faker.js#944]
I got this IBAN generated: `GE10440066518090154041`, which is for Georgia.
According to the [Wikipedia article](https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country), the format for an IBAN for Georgia is `GEkk bbcc cccc cccc cccc cc` (which is also used like that in the [lib/iban.js](https://github.com/Marak/faker.js/blob/master/lib/iban.js)), so there should be 2 alpha chars at position 5 and 6, which is not the case for the IBAN that faker generated.

**Comment by Marak** [comment]
Okay.

**Comment by Moosh-be** [comment]
@christianbaumann I've try to write test to validate issue are solved (and so no regression later)

If you can Review … (because  i'm PHP Dev, JS is new) 
It's works but  I Don't know it's "clean"
