### ISSUE TITLE
Bug with middle name using belarussian language

### ISSUE THREAD

**Issue by katemalets** [Marak/faker.js#948]
![image](https://user-images.githubusercontent.com/58632711/89218020-f0079300-d5d5-11ea-8377-4cc93e144f94.png)
Using function nameWithMiddle() I found Dr, Mrs and other titles in output.

**Comment by Moosh-be** [comment]
AND ?   What's the good answer ?

**Comment by Marak** [comment]
Closing for lack of information.

Please feel free to re-open with more information or a PR.
