### ISSUE TITLE
Local of Nepal language is ne, not nep

### ISSUE THREAD

**Issue by Moosh-be** [Marak/faker.js#956]
www.localeplanet.com/icu/ne/index.html

If agree, I can change an PR.

**Comment by Marak** [comment]
Agree

**Comment by Moosh-be** [comment]
WIP :)

**Comment by Moosh-be** [comment]
WIP :)

**Comment by Moosh-be** [comment]
Done in #957 , ready for review.

**Comment by Marak** [comment]
This should be resolved in latest published version.

Closing.

Thank you for your contributions @Moosh-be !
