### ISSUE TITLE
Proper encoding for cyrillic letters needed

### ISSUE THREAD

**Issue by madebyalex** [Marak/faker.js#963]
Currently all data generated for countries which use cyrillic letters is totally unreadable. For example, a russian random name looks like "ÐÐ½Ð¶ÐµÐ»Ð° Ð¡Ð¾ÐºÐ¾Ð»Ð¾Ð²Ð°". And I may you assure that it's not written correctly 🙂

The result should be "Анжела Соколова" instead (or "Anzhela Sokolova" if turned into latin symbols).
Please use proper encoding. Thank you in advance.

And thank you for the interesting and useful project! 👍

**Comment by Marak** [comment]
?

**Comment by Marak** [comment]
@madebyalex `hook.io` is not `faker.js`.

If you suspect there is a problem with the `faker.js` library you will need to open up a Pull Request here with a failing unit test.

Thank you.
