### ISSUE TITLE
faker.commerce.productDescription() is not a function

### ISSUE THREAD

**Issue by abhidp** [Marak/faker.js#970]
I am opening this bug again because the previous bug was closed without any comments. https://github.com/Marak/faker.js/issues/967

Can you please mention the reason before closing the bug?

Issue: cannot use faker.commerce.productDescription() 

Code Snippet:

``` javascript
const faker = require('faker');
const description = faker.commerce.productDescription();
console.log('Description : ', description);
```

Error: `(node:15071) UnhandledPromiseRejectionWarning: TypeError: faker.commerce.productDescription is not a function`

I am using:
`"faker": "^4.1.0"`

According to the documentation there is a productDescription under the commerce section.
But can't call this function in my code.

**Comment by Marak** [comment]
@abhidp

Thank you for your contributions.

There is a difference between the `master` version on Github and the specific version you may or may not be using locally.
