### ISSUE TITLE
Can we get a milestone for version 5.0.0 or 4.2.0

### ISSUE THREAD

**Issue by Andrew5569** [Marak/faker.js#971]
Could we get a [milestone](https://docs.github.com/en/github/managing-your-work-on-github/about-milestones) for version 5.0.0 or 4.2.0 of faker? 

I know a lot of people are anticipating the next release of faker. Providing a milestone could provide a way for people to track the progress towards the next release. It would also provide a list of priorities for people who wish to contribute to the project. I would be willing to contribute to the next release and I've read comments from others who feel the same way.

**Comment by Marak** [comment]
Sounds good @Andrew5569 

Looking forward to seeing the list and milestone, thanks!
