### ISSUE TITLE
Faker.random.word returns '24/365'

### ISSUE THREAD

**Issue by elkemper** [Marak/faker.js#973]
Hey!
I'm not sure, but it seems that slash char is not best candidate for "word", and it can cause failures, when random.word() is used for salting file names. It causes.

**Comment by Marak** [comment]
@elkemper -

Are you able to reproduce this? Can you find the place in the code where these values are being returned?

**Comment by elkemper** [comment]
@Marak 
This is inconsistent behavior, because this is random namespace. but, if you invoke Faker.random.word() for, i think 20000 times, you can find this value.

**Comment by Marak** [comment]
@elkemper - 

Sounds good. 

Let us know what you can find. 

PRs are welcome.

**Comment by elkemper** [comment]
@Marak 
Well, I've fixed only for EN locale, but, here it is
https://github.com/Marak/faker.js/pull/980

**Comment by Marak** [comment]
@elkemper - Why not use `System.fileName()` method instead?
