### ISSUE TITLE
Install with Meteor leads to Bus error: 10or web.browser    

### ISSUE THREAD

**Issue by ppedrazzi** [Marak/faker.js#982]
Working meteor app breaks on npm install of faker and restart.

Fatal error in terminal:
Bus error: 10or web.browser

**Comment by Marak** [comment]
???

**Comment by lenolomokgosi** [comment]
Hi, got similar issue.

Test app running ok before installation. You'll see after installation I get the error

![F331BC50-1081-4555-90E2-C22DCDB01AB6_4_5005_c](https://user-images.githubusercontent.com/21595620/96790608-fc3e0800-13ee-11eb-90b1-baf67afbeced.jpeg)

**Comment by Floriferous** [comment]
Same here, was hard to find the culprit, don't have any error logged either.

**Comment by Floriferous** [comment]
I'm assuming this should be reopened?
