### ISSUE TITLE
Wrong country names for pt-BR locales

### ISSUE THREAD

**Issue by Lukazovic** [Marak/faker.js#996]
I've noticed there are a lot of wrong country names in the [country.js](https://github.com/Marak/faker.js/blob/master/lib/locales/pt_BR/address/country.js) file in the [pt_BR](https://github.com/Marak/faker.js/tree/master/lib/locales/pt_BR) folder.

Example:  [4th line](https://github.com/Marak/faker.js/blob/master/lib/locales/pt_BR/address/country.js#L4), "Algéria" should be "Argélia".

I'm working on it.

**Comment by Marak** [comment]
This should be resolved with: https://github.com/Marak/faker.js/pull/1032
